"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { X } from "lucide-react";
import { createBulkShifts } from "@/app/actions/shifts";
import { Drawer } from "@/components/admin/drawer";
import { SHIFT_STATUS_LABELS } from "@/lib/admin/projects/project-detail-rules";
import { bulkResolvedShiftSchema } from "@/lib/admin/projects/bulk-shift-form-schema";
import { generateDates, normalizeOverride, resolveShiftConfig, type BulkShiftConfig, type BulkShiftOverrides } from "@/lib/admin/projects/bulk-shift-helpers";
import { SHIFT_STATUSES } from "@/lib/admin/projects/shift-form-schema";
import type { ShiftFormOptions } from "@/lib/admin/projects/shift-form-types";
import { ShiftFormError } from "./shift-form-error";

const control = "min-h-11 w-full rounded-md border border-border bg-surface px-3 py-2 text-sm text-foreground outline-none focus:border-info focus:ring-2 focus:ring-info-subtle";
const secondary = "inline-flex min-h-11 items-center justify-center rounded-md border border-border px-4 text-sm font-semibold text-foreground-secondary hover:bg-background-subtle focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-info";
const weekdayLabels = ["日", "月", "火", "水", "木", "金", "土"];
const displayDate = (date: string) => new Intl.DateTimeFormat("ja-JP", { timeZone: "UTC", month: "numeric", day: "numeric", weekday: "short" }).format(new Date(`${date}T00:00:00Z`));

export function BulkShiftCreateForm({ options }: { options: ShiftFormOptions }) {
  const [base, setBase] = useState<BulkShiftConfig>({ startTime: "09:00", endTime: "18:00", endsNextDay: false, requiredWorkers: "1", breakMinutes: "", deadlineEnabled: false, deadlineDaysBefore: "2", deadlineTime: "18:00", status: options.job.status === "draft" ? "draft" : "recruiting" });
  const [rangeStart, setRangeStart] = useState("");
  const [rangeEnd, setRangeEnd] = useState("");
  const [weekdays, setWeekdays] = useState([1, 2, 3, 4, 5]);
  const [dates, setDates] = useState<string[]>([]);
  const [manualDate, setManualDate] = useState("");
  const [overrides, setOverrides] = useState<BulkShiftOverrides>({});
  const [selectedDate, setSelectedDate] = useState<string | null>(null);
  const [overrideDraft, setOverrideDraft] = useState<BulkShiftConfig>(base);
  const [preview, setPreview] = useState(false);
  const [rootError, setRootError] = useState<string>();
  const [isSubmitting, setSubmitting] = useState(false);

  const resolved = useMemo(() => dates.map((date) => ({ date, ...resolveShiftConfig(base, overrides[date]) })), [base, dates, overrides]);
  const dateErrors = useMemo(() => Object.fromEntries(resolved.flatMap((shift) => { const result = bulkResolvedShiftSchema.safeParse(shift); return result.success ? [] : [[shift.date, result.error.issues[0]?.message ?? "入力内容を確認してください。"]]; })), [resolved]);
  const updateBase = <K extends keyof BulkShiftConfig>(key: K, value: BulkShiftConfig[K]) => setBase((current) => ({ ...current, [key]: value }));
  const generate = () => { const next = generateDates(rangeStart, rangeEnd, weekdays); setDates(next); setOverrides((current) => Object.fromEntries(Object.entries(current).filter(([date]) => next.includes(date)))); setRootError(next.length === 0 ? "期間と曜日を確認してください。" : undefined); };
  const addDate = () => { if (!manualDate) return; if (dates.includes(manualDate)) { setRootError("同じ勤務日は追加できません。"); return; } setDates((current) => [...current, manualDate].sort()); setManualDate(""); setRootError(undefined); };
  const openOverride = (date: string) => { setSelectedDate(date); setOverrideDraft(resolveShiftConfig(base, overrides[date])); };
  const saveOverride = () => { if (!selectedDate) return; const normalized = normalizeOverride(base, overrideDraft); setOverrides((current) => { const next = { ...current }; if (Object.keys(normalized).length === 0) delete next[selectedDate]; else next[selectedDate] = normalized; return next; }); setSelectedDate(null); };
  const resetOverride = (date: string) => setOverrides((current) => { const next = { ...current }; delete next[date]; return next; });
  const submit = async () => { if (dates.length === 0 || Object.keys(dateErrors).length > 0) return; setSubmitting(true); setRootError(undefined); const result = await createBulkShifts(options.project.id, options.job.id, { shifts: resolved }); if (result?.message) setRootError(result.message); setSubmitting(false); };

  return <div className="space-y-6">
    <ShiftFormError message={rootError} />
    <section aria-labelledby="bulk-context-title" className="rounded-lg border border-border bg-surface p-4 sm:p-6"><h2 id="bulk-context-title" className="font-semibold text-foreground">対象案件・業務</h2><p className="mt-2 font-semibold text-foreground">{options.project.name}</p><p className="mt-1 text-sm text-foreground-secondary">{options.job.name} · {options.job.workplaceName}</p></section>
    <section aria-labelledby="common-title" className="rounded-lg border border-border bg-surface p-4 sm:p-6"><h2 id="common-title" className="text-lg font-semibold text-foreground">1. 共通設定</h2><p className="mt-1 text-sm text-foreground-secondary">日別設定をしていない勤務日に適用されます。</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="開始時刻"><input type="time" value={base.startTime} onChange={(event) => updateBase("startTime", event.target.value)} className={control} /></Field><Field label="終了時刻"><input type="time" value={base.endTime} onChange={(event) => updateBase("endTime", event.target.value)} className={control} /></Field><Field label="必要人数"><input type="number" min="1" value={base.requiredWorkers} onChange={(event) => updateBase("requiredWorkers", event.target.value)} className={control} /></Field><Field label="休憩（分）"><input type="number" min="0" value={base.breakMinutes} onChange={(event) => updateBase("breakMinutes", event.target.value)} className={control} /></Field></div><label className="mt-3 flex min-h-11 items-center gap-3 text-sm font-medium"><input type="checkbox" checked={base.endsNextDay} onChange={(event) => updateBase("endsNextDay", event.target.checked)} className="size-5" />終了は翌日</label><label className="flex min-h-11 items-center gap-3 text-sm font-medium"><input type="checkbox" checked={base.deadlineEnabled} onChange={(event) => updateBase("deadlineEnabled", event.target.checked)} className="size-5" />応募締切を設定</label>{base.deadlineEnabled && <div className="grid gap-4 sm:grid-cols-2"><Field label="勤務日の何日前"><input type="number" min="0" value={base.deadlineDaysBefore} onChange={(event) => updateBase("deadlineDaysBefore", event.target.value)} className={control} /></Field><Field label="締切時刻"><input type="time" value={base.deadlineTime} onChange={(event) => updateBase("deadlineTime", event.target.value)} className={control} /></Field></div>}<div className="mt-4"><Field label="状態"><select value={base.status} onChange={(event) => updateBase("status", event.target.value as BulkShiftConfig["status"])} className={control}>{SHIFT_STATUSES.map((status) => <option key={status} value={status}>{SHIFT_STATUS_LABELS[status]}</option>)}</select></Field></div></section>
    <section aria-labelledby="dates-title" className="rounded-lg border border-border bg-surface p-4 sm:p-6"><h2 id="dates-title" className="text-lg font-semibold text-foreground">2. 日程</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="開始日"><input type="date" value={rangeStart} onChange={(event) => setRangeStart(event.target.value)} className={control} /></Field><Field label="終了日"><input type="date" value={rangeEnd} onChange={(event) => setRangeEnd(event.target.value)} className={control} /></Field></div><fieldset className="mt-4"><legend className="text-sm font-medium text-foreground-secondary">曜日</legend><div className="mt-2 flex flex-wrap gap-2">{weekdayLabels.map((label, index) => <label key={label} className="inline-flex min-h-11 min-w-11 items-center justify-center gap-2 rounded-md border border-border px-3 text-sm"><input type="checkbox" checked={weekdays.includes(index)} onChange={() => setWeekdays((current) => current.includes(index) ? current.filter((day) => day !== index) : [...current, index])} />{label}</label>)}</div></fieldset><button type="button" onClick={generate} className={`${secondary} mt-4`}>対象日を生成</button><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input type="date" aria-label="任意日を追加" value={manualDate} onChange={(event) => setManualDate(event.target.value)} className={control} /><button type="button" onClick={addDate} className={secondary}>任意日を追加</button></div></section>
    <section aria-labelledby="adjust-title" className="rounded-lg border border-border bg-surface"><div className="p-4 sm:p-6"><h2 id="adjust-title" className="text-lg font-semibold text-foreground">3. 日別調整</h2><p className="mt-1 text-sm text-foreground-secondary">{dates.length}日を作成対象にしています。</p></div>{dates.length === 0 ? <p className="border-t border-border p-6 text-sm text-foreground-muted">日程を生成、または任意日を追加してください。</p> : <ul className="divide-y divide-border">{resolved.map((shift) => <li key={shift.date} className="grid gap-3 px-4 py-4 sm:px-6 md:grid-cols-[minmax(8rem,1fr)_minmax(9rem,1fr)_minmax(6rem,.7fr)_auto] md:items-center"><div><p className="font-semibold text-foreground">{displayDate(shift.date)}</p>{dateErrors[shift.date] && <p className="mt-1 text-sm text-danger" role="alert">エラーあり：{dateErrors[shift.date]}</p>}</div><p className="text-sm text-foreground-secondary">{shift.startTime}〜{shift.endTime}{shift.endsNextDay ? "（翌日）" : ""}</p><p className="text-sm text-foreground-secondary">{shift.requiredWorkers}名</p><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${overrides[shift.date] ? "bg-info-subtle text-link" : "bg-background-subtle text-foreground-secondary"}`}>{overrides[shift.date] ? "個別設定あり" : "共通設定"}</span><button type="button" onClick={() => openOverride(shift.date)} className={secondary}>編集</button>{overrides[shift.date] && <button type="button" onClick={() => resetOverride(shift.date)} className={secondary}>共通設定に戻す</button>}<button type="button" onClick={() => { setDates((current) => current.filter((date) => date !== shift.date)); resetOverride(shift.date); }} className={`${secondary} text-danger`}>除外</button></div></li>)}</ul>}</section>
    <section aria-labelledby="preview-title" className="rounded-lg border border-border bg-surface p-4 sm:p-6"><h2 id="preview-title" className="text-lg font-semibold text-foreground">4. 確認</h2><p className="mt-2 font-semibold text-foreground">{dates.length}件の独立したシフトを作成します</p><p className="mt-1 text-sm text-foreground-secondary">個別設定 {Object.keys(overrides).length}日 / エラー {Object.keys(dateErrors).length}日</p>{preview && <ul className="mt-4 divide-y divide-border rounded-lg border border-border">{resolved.map((shift) => <li key={shift.date} className="flex flex-wrap justify-between gap-3 px-4 py-3 text-sm"><span className="font-semibold">{displayDate(shift.date)}</span><span>{shift.startTime}〜{shift.endTime} · {shift.requiredWorkers}名</span><span>{overrides[shift.date] ? "個別" : "共通"}</span></li>)}</ul>}<button type="button" onClick={() => setPreview((value) => !value)} className={`${secondary} mt-4`}>{preview ? "プレビューを閉じる" : "プレビューを表示"}</button></section>
    <div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><Link href={`/admin/projects/${options.project.id}`} className={secondary}>キャンセル</Link><button type="button" onClick={submit} disabled={isSubmitting || dates.length === 0 || Object.keys(dateErrors).length > 0} className="min-h-11 rounded-md bg-primary px-5 text-sm font-semibold text-primary-foreground hover:bg-primary-hover focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-info disabled:cursor-not-allowed disabled:bg-foreground-muted">{isSubmitting ? "作成中..." : `${dates.length}件のシフトを一括作成`}</button></div>
    <Drawer open={Boolean(selectedDate)} titleId="bulk-override-title" onClose={() => setSelectedDate(null)}><header className="sticky top-0 z-10 flex items-start justify-between border-b border-border bg-surface p-4 sm:p-6"><div><h2 id="bulk-override-title" className="text-xl font-semibold">日別設定</h2><p className="mt-1 text-sm text-foreground-secondary">{selectedDate ? displayDate(selectedDate) : ""}</p></div><button type="button" autoFocus aria-label="日別設定を閉じる" onClick={() => setSelectedDate(null)} className="flex size-11 items-center justify-center rounded-md"><X aria-hidden="true" className="size-5" /></button></header><div className="space-y-4 p-4 sm:p-6"><div className="grid gap-4 sm:grid-cols-2"><Field label="開始時刻"><input type="time" value={overrideDraft.startTime} onChange={(event) => setOverrideDraft((current) => ({ ...current, startTime: event.target.value }))} className={control} /></Field><Field label="終了時刻"><input type="time" value={overrideDraft.endTime} onChange={(event) => setOverrideDraft((current) => ({ ...current, endTime: event.target.value }))} className={control} /></Field><Field label="必要人数"><input type="number" min="1" value={overrideDraft.requiredWorkers} onChange={(event) => setOverrideDraft((current) => ({ ...current, requiredWorkers: event.target.value }))} className={control} /></Field><Field label="休憩（分）"><input type="number" min="0" value={overrideDraft.breakMinutes} onChange={(event) => setOverrideDraft((current) => ({ ...current, breakMinutes: event.target.value }))} className={control} /></Field></div><div className="flex justify-end gap-3 border-t border-border pt-4"><button type="button" onClick={() => setSelectedDate(null)} className={secondary}>キャンセル</button><button type="button" onClick={saveOverride} className="min-h-11 rounded-md bg-primary px-5 text-sm font-semibold text-primary-foreground">日別設定を保存</button></div></div></Drawer>
  </div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-sm font-medium text-foreground-secondary">{label}{children}</label>; }
