"use client";
import Link from "next/link";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { createShift } from "@/app/actions/shifts";
import { SHIFT_STATUS_LABELS } from "@/lib/admin/projects/project-detail-rules";
import { SHIFT_STATUSES, shiftFormSchema, type ShiftFormValues } from "@/lib/admin/projects/shift-form-schema";
import type { ShiftFormOptions } from "@/lib/admin/projects/shift-form-types";
import { ShiftFormError } from "./shift-form-error";

const control = "mt-1.5 min-h-11 w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm text-slate-950 outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-100";
export function ShiftCreateForm({ options }: { options: ShiftFormOptions }) {
  const defaultStatus = options.job.status === "draft" ? "draft" : "recruiting";
  const { register, handleSubmit, setError, formState: { errors, isSubmitting } } = useForm<ShiftFormValues>({ resolver: zodResolver(shiftFormSchema), defaultValues: { start_date: "", start_time: "", end_date: "", end_time: "", required_workers: "1", break_minutes: "", deadline_date: "", deadline_time: "", status: defaultStatus } });
  const submit = handleSubmit(async (values) => { const result = await createShift(options.project.id, options.job.id, values); if (result.fieldErrors) for (const [field, message] of Object.entries(result.fieldErrors)) if (message) setError(field as keyof ShiftFormValues, { message }); if (result.message) setError("root", { message: result.message }); });
  const error = (field: keyof ShiftFormValues) => errors[field]?.message;
  return <form onSubmit={submit} noValidate className="space-y-5 rounded-lg border border-slate-200 bg-white p-4 sm:p-6">
    <ShiftFormError message={errors.root?.message} />
    <section aria-labelledby="context-title" className="rounded-md bg-slate-50 p-4"><h2 id="context-title" className="text-sm font-semibold text-slate-700">対象業務</h2><p className="mt-2 font-semibold text-slate-950">{options.job.name}</p><p className="mt-1 text-sm text-slate-600">{options.job.workplaceName}</p>{(options.job.hourlyWage !== null || options.job.transportationFeeCap !== null) && <p className="mt-2 text-sm text-slate-600">時給 {options.job.hourlyWage ?? "未設定"}円 / 交通費上限 {options.job.transportationFeeCap ?? "未設定"}円</p>}</section>
    <div className="grid gap-5 sm:grid-cols-2"><Field name="start_date" label="開始日" required error={error("start_date")}><input type="date" {...register("start_date")} aria-invalid={Boolean(errors.start_date)} aria-describedby={errors.start_date ? "start_date-error" : undefined} className={control} /></Field><Field name="start_time" label="開始時刻" required error={error("start_time")}><input type="time" {...register("start_time")} aria-invalid={Boolean(errors.start_time)} aria-describedby={errors.start_time ? "start_time-error" : undefined} className={control} /></Field></div>
    <div className="grid gap-5 sm:grid-cols-2"><Field name="end_date" label="終了日" required error={error("end_date")}><input type="date" {...register("end_date")} aria-invalid={Boolean(errors.end_date)} aria-describedby={errors.end_date ? "end_date-error" : undefined} className={control} /></Field><Field name="end_time" label="終了時刻" required error={error("end_time")}><input type="time" {...register("end_time")} aria-invalid={Boolean(errors.end_time)} aria-describedby={errors.end_time ? "end_time-error" : undefined} className={control} /></Field></div>
    <div className="grid gap-5 sm:grid-cols-2"><Field name="required_workers" label="必要人数" required error={error("required_workers")}><div className="flex items-center gap-2"><input type="number" min="1" step="1" {...register("required_workers")} aria-invalid={Boolean(errors.required_workers)} className={control} /><span className="mt-1.5 text-sm text-slate-600">名</span></div></Field><Field name="break_minutes" label="休憩時間" error={error("break_minutes")}><div className="flex items-center gap-2"><input type="number" min="0" step="1" {...register("break_minutes")} aria-invalid={Boolean(errors.break_minutes)} className={control} /><span className="mt-1.5 text-sm text-slate-600">分</span></div></Field></div>
    <fieldset><legend className="text-sm font-medium text-slate-800">応募締切</legend><div className="grid gap-5 sm:grid-cols-2"><Field name="deadline_date" label="日付" error={error("deadline_date")}><input type="date" {...register("deadline_date")} aria-invalid={Boolean(errors.deadline_date)} className={control} /></Field><Field name="deadline_time" label="時刻" error={error("deadline_time")}><input type="time" {...register("deadline_time")} aria-invalid={Boolean(errors.deadline_time)} className={control} /></Field></div></fieldset>
    <Field name="status" label="状態" required error={error("status")}><select {...register("status")} aria-invalid={Boolean(errors.status)} className={control}>{SHIFT_STATUSES.map((status) => <option key={status} value={status}>{SHIFT_STATUS_LABELS[status]}</option>)}</select></Field>
    <div className="flex flex-col-reverse gap-3 border-t border-slate-200 pt-5 sm:flex-row sm:justify-end"><Link href={`/admin/projects/${options.project.id}`} className="inline-flex min-h-11 items-center justify-center rounded-md border border-slate-300 px-5 text-sm font-semibold text-slate-700 hover:bg-slate-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600">キャンセル</Link><button type="submit" disabled={isSubmitting} className="min-h-11 rounded-md bg-blue-700 px-5 text-sm font-semibold text-white hover:bg-blue-800 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600 disabled:cursor-not-allowed disabled:bg-slate-400">{isSubmitting ? "シフトを追加中..." : "シフトを追加"}</button></div>
  </form>;
}
function Field({ name, label, required, error, children }: { name: string; label: string; required?: boolean; error?: string; children: React.ReactNode }) { return <label className="block text-sm font-medium text-slate-800">{label}{required && <span className="ml-1 text-red-700">*</span>}{children}{error && <span id={`${name}-error`} className="mt-1.5 block text-sm text-red-700">{error}</span>}</label>; }
