"use server";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { getEditActor } from "@/lib/admin/edit/get-edit-actor";
import { editConflictMessage,editForbiddenMessage,editGeneralErrorMessage } from "@/lib/admin/edit/edit-action-result";
import { clientSchema,masterUpdateSchema } from "@/lib/admin/masters/master-rules";
import type { MasterActionResult } from "@/lib/admin/masters/master-types";
const fields=(issues:{path:PropertyKey[];message:string}[])=>Object.fromEntries(issues.map(i=>[String(i.path[0]),i.message]));
export async function saveClient(input:unknown):Promise<MasterActionResult>{const value=typeof input==="object"&&input?input as Record<string,unknown>:{};const parsed=clientSchema.safeParse(value);if(!parsed.success)return{ok:false,type:"validation",message:"入力内容を確認してください。",fieldErrors:fields(parsed.error.issues)};const actor=await getEditActor();if(!actor.ok)return{ok:false,type:"forbidden",message:editForbiddenMessage};try{const supabase=await createClient();const branch=await supabase.from("branches").select("id").eq("id",parsed.data.branchId).maybeSingle();if(branch.error||!branch.data)return{ok:false,type:"forbidden",message:editForbiddenMessage};const update=masterUpdateSchema.safeParse(value);if(!update.success){const result=await supabase.from("clients").insert({branch_id:branch.data.id,name:parsed.data.name,note:parsed.data.note,is_active:parsed.data.isActive}).select("id,updated_at").single();if(result.error)throw result.error;revalidatePath("/admin/clients");revalidatePath("/admin/projects");return{ok:true,type:"created",id:result.data.id,updatedAt:result.data.updated_at};}const current=await supabase.from("clients").select("id,branch_id,name,note,is_active,updated_at").eq("id",update.data.id).maybeSingle();if(current.error)throw current.error;if(!current.data)return{ok:false,type:"not_found",message:"対象が見つかりません。"};if(current.data.branch_id!==parsed.data.branchId)return{ok:false,type:"validation",message:"支店は変更できません。",fieldErrors:{branchId:"支店は変更できません。"}};if(current.data.updated_at!==update.data.expectedUpdatedAt)return{ok:false,type:"conflict",message:editConflictMessage};if(current.data.name===parsed.data.name&&current.data.note===parsed.data.note&&current.data.is_active===parsed.data.isActive)return{ok:true,type:"no_change",id:current.data.id,updatedAt:current.data.updated_at};const result=await supabase.from("clients").update({name:parsed.data.name,note:parsed.data.note,is_active:parsed.data.isActive}).eq("id",current.data.id).eq("updated_at",update.data.expectedUpdatedAt).select("id,updated_at");if(result.error)throw result.error;if(result.data.length!==1)return{ok:false,type:"conflict",message:editConflictMessage};revalidatePath("/admin/clients");revalidatePath("/admin/projects");return{ok:true,type:"updated",id:result.data[0].id,updatedAt:result.data[0].updated_at};}catch(error){console.error("Failed to save client",error);return{ok:false,type:"error",message:editGeneralErrorMessage};}}
