"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { getCurrentProfile } from "@/lib/auth/get-current-profile";
import type { CredentialActionResult } from "@/lib/admin/staff-credentials/types";

const code=z.string().trim().min(1,"コードを入力してください。").max(50).regex(/^[A-Za-z0-9][A-Za-z0-9._-]*$/,"英数字と . _ - を使用してください。");
const base=z.object({id:z.string().uuid().optional(),code:code.optional(),name:z.string().trim().min(1,"名称を入力してください。").max(100),description:z.string().trim().max(500).optional().default(""),isActive:z.boolean().default(true)});
const skillSchema=base.superRefine((v,c)=>{if(!v.id&&!v.code)c.addIssue({code:"custom",path:["code"],message:"コードを入力してください。"})});
const qualificationSchema=base.extend({expiryPolicy:z.enum(["none","optional","required"])}).superRefine((v,c)=>{if(!v.id&&!v.code)c.addIssue({code:"custom",path:["code"],message:"コードを入力してください。"})});
const databaseUuid=z.string().regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,"IDが正しくありません。");
const workerSkillSchema=z.object({workerId:databaseUuid,skillId:databaseUuid,acquiredOn:z.string().date().nullable(),isActive:z.boolean()});
const workerQualificationSchema=z.object({workerId:databaseUuid,qualificationId:databaseUuid,credentialNumber:z.string().trim().max(100).nullable(),issuedOn:z.string().date().nullable(),validFrom:z.string().date().nullable(),expiresOn:z.string().date().nullable(),revoked:z.boolean()});
const fieldErrors=(issues:z.core.$ZodIssue[])=>Object.fromEntries(issues.map(issue=>[String(issue.path[0]??"form"),issue.message]));
async function authorized(){const actor=await getCurrentProfile();return actor.status==="authenticated"&&actor.profile.account_type==="system_admin";}
const fail=(message:string):CredentialActionResult=>({ok:false,type:"error",message});
function mapDbError(error:{code?:string;message?:string}):CredentialActionResult{if(error.code==="42501")return{ok:false,type:"forbidden",message:"この操作はSystem Adminのみ実行できます。"};const m=error.message??"";if(error.code==="23505")return{ok:false,type:"validation",message:"同じコードが既に登録されています。"};if(m.includes("inactive_skill")||m.includes("inactive_qualification"))return{ok:false,type:"validation",message:"無効なマスタは新しく付与できません。"};if(m.includes("expiry_required"))return{ok:false,type:"validation",message:"この資格には有効期限が必要です。"};if(m.includes("expiry_forbidden"))return{ok:false,type:"validation",message:"この資格には有効期限を設定できません。"};if(m.includes("policy_conflicts"))return{ok:false,type:"validation",message:"既存の保有資格と矛盾する有効期限ポリシーです。"};return fail("保存できませんでした。");}
export async function saveSkillMaster(input:unknown):Promise<CredentialActionResult>{const p=skillSchema.safeParse(input);if(!p.success)return{ok:false,type:"validation",message:"入力内容を確認してください。",fieldErrors:fieldErrors(p.error.issues)};if(!await authorized())return{ok:false,type:"forbidden",message:"この操作はSystem Adminのみ実行できます。"};try{const s=await createClient();const r=p.data.id?await s.rpc("update_skill_master",{p_skill_id:p.data.id,p_name:p.data.name,p_description:p.data.description||null,p_is_active:p.data.isActive}):await s.rpc("create_skill_master",{p_code:p.data.code!,p_name:p.data.name,p_description:p.data.description||null});if(r.error)return mapDbError(r.error);revalidatePath("/admin/staff-credentials");revalidatePath("/admin/workers");return{ok:true};}catch{return fail("スキルを保存できませんでした。");}}
export async function saveQualificationMaster(input:unknown):Promise<CredentialActionResult>{const p=qualificationSchema.safeParse(input);if(!p.success)return{ok:false,type:"validation",message:"入力内容を確認してください。",fieldErrors:fieldErrors(p.error.issues)};if(!await authorized())return{ok:false,type:"forbidden",message:"この操作はSystem Adminのみ実行できます。"};try{const s=await createClient();const r=p.data.id?await s.rpc("update_qualification_master",{p_qualification_id:p.data.id,p_name:p.data.name,p_description:p.data.description||null,p_expiry_policy:p.data.expiryPolicy,p_is_active:p.data.isActive}):await s.rpc("create_qualification_master",{p_code:p.data.code!,p_name:p.data.name,p_description:p.data.description||null,p_expiry_policy:p.data.expiryPolicy});if(r.error)return mapDbError(r.error);revalidatePath("/admin/staff-credentials");revalidatePath("/admin/workers");return{ok:true};}catch{return fail("資格を保存できませんでした。");}}
export async function saveWorkerSkill(input:unknown):Promise<CredentialActionResult>{const p=workerSkillSchema.safeParse(input);if(!p.success)return{ok:false,type:"validation",message:"入力内容を確認してください。",fieldErrors:fieldErrors(p.error.issues)};if(!await authorized())return{ok:false,type:"forbidden",message:"この操作はSystem Adminのみ実行できます。"};const s=await createClient();const r=await s.rpc("set_worker_skill_holding",{p_worker_id:p.data.workerId,p_skill_id:p.data.skillId,p_acquired_on:p.data.acquiredOn,p_is_active:p.data.isActive});if(r.error)return mapDbError(r.error);revalidatePath(`/admin/workers/${p.data.workerId}`);return{ok:true};}
export async function saveWorkerQualification(input:unknown):Promise<CredentialActionResult>{const p=workerQualificationSchema.safeParse(input);if(!p.success)return{ok:false,type:"validation",message:"入力内容を確認してください。",fieldErrors:fieldErrors(p.error.issues)};if(!await authorized())return{ok:false,type:"forbidden",message:"この操作はSystem Adminのみ実行できます。"};const s=await createClient();const r=await s.rpc("set_worker_qualification_holding",{p_worker_id:p.data.workerId,p_qualification_id:p.data.qualificationId,p_credential_number:p.data.credentialNumber||null,p_issued_on:p.data.issuedOn,p_valid_from:p.data.validFrom,p_expires_on:p.data.expiresOn,p_revoked_at:p.data.revoked?new Date().toISOString():null});if(r.error)return mapDbError(r.error);revalidatePath(`/admin/workers/${p.data.workerId}`);return{ok:true};}
