"use server";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { getEditActor } from "@/lib/admin/edit/get-edit-actor";
import { editConflictMessage,editForbiddenMessage,editGeneralErrorMessage } from "@/lib/admin/edit/edit-action-result";
import { masterUpdateSchema,workplaceSchema } from "@/lib/admin/masters/master-rules";
import type { MasterActionResult } from "@/lib/admin/masters/master-types";
const fields=(issues:{path:PropertyKey[];message:string}[])=>Object.fromEntries(issues.map(i=>[String(i.path[0]),i.message]));
export async function saveWorkplace(input:unknown):Promise<MasterActionResult>{const value=typeof input==="object"&&input?input as Record<string,unknown>:{};const parsed=workplaceSchema.safeParse(value);if(!parsed.success)return{ok:false,type:"validation",message:"入力内容を確認してください。",fieldErrors:fields(parsed.error.issues)};const actor=await getEditActor();if(!actor.ok)return{ok:false,type:"forbidden",message:editForbiddenMessage};try{const supabase=await createClient();const branch=await supabase.from("branches").select("id").eq("id",parsed.data.branchId).maybeSingle();if(branch.error||!branch.data)return{ok:false,type:"forbidden",message:editForbiddenMessage};const values={name:parsed.data.name,postal_code:parsed.data.postalCode,address:parsed.data.address,default_transport_note:parsed.data.defaultTransportNote,access_note:parsed.data.accessNote,meeting_note:parsed.data.meetingNote,is_active:parsed.data.isActive};const update=masterUpdateSchema.safeParse(value);if(!update.success){const result=await supabase.from("workplaces").insert({branch_id:branch.data.id,...values}).select("id,updated_at").single();if(result.error)throw result.error;revalidatePath("/admin/workplaces");revalidatePath("/admin/projects");return{ok:true,type:"created",id:result.data.id,updatedAt:result.data.updated_at};}const current=await supabase.from("workplaces").select("id,branch_id,name,postal_code,address,default_transport_note,access_note,meeting_note,is_active,updated_at").eq("id",update.data.id).maybeSingle();if(current.error)throw current.error;if(!current.data)return{ok:false,type:"not_found",message:"対象が見つかりません。"};if(current.data.branch_id!==parsed.data.branchId)return{ok:false,type:"validation",message:"支店は変更できません。",fieldErrors:{branchId:"支店は変更できません。"}};if(current.data.updated_at!==update.data.expectedUpdatedAt)return{ok:false,type:"conflict",message:editConflictMessage};const result=await supabase.from("workplaces").update(values).eq("id",current.data.id).eq("updated_at",update.data.expectedUpdatedAt).select("id,updated_at");if(result.error)throw result.error;if(result.data.length!==1)return{ok:false,type:"conflict",message:editConflictMessage};revalidatePath("/admin/workplaces");revalidatePath("/admin/projects");return{ok:true,type:"updated",id:result.data[0].id,updatedAt:result.data[0].updated_at};}catch(error){console.error("Failed to save workplace",error);return{ok:false,type:"error",message:editGeneralErrorMessage};}}
