import "server-only";
import { requireAdmin } from "@/lib/auth/require-admin";
import { createClient } from "@/lib/supabase/server";
import { readAllPages } from "@/lib/admin/shifts/read-all-pages";
import { buildDayOfItems,dayOfRange,type DayOfInput,type DayOfQuery } from "./day-of-rules";

type PreShiftRow={can_work:boolean;submitted_at:string};
type IncidentRow={id:string;assignment_id:string;state:"open"|"acknowledged";category:string;created_at:string};
type Row={id:string;shift_slot_id:string;status:string;worker_id:string;workers:{display_name:string;staff_code:string};shift_slots:{id:string;starts_at:string;ends_at:string;required_workers:number;jobs:{id:string;name:string;projects:{id:string;name:string};workplaces:{name:string}}};pre_shift_confirmations:PreShiftRow|PreShiftRow[]|null};
export async function getDayOf(query:DayOfQuery,now=new Date()){
  await requireAdmin();
  try{const supabase=await createClient();const range=dayOfRange(query.date);const rows=await readAllPages<Row>(async(from,to)=>{const result=await supabase.from("assignments").select(`id,shift_slot_id,status,worker_id,workers!inner(display_name,staff_code),shift_slots!inner(id,starts_at,ends_at,required_workers,jobs!inner(id,name,projects!inner(id,name),workplaces!inner(name))),pre_shift_confirmations(can_work,submitted_at)`,{count:"exact"}).in("status",["assigned","confirmed","completed","absent","no_show"]).gte("shift_slots.starts_at",range.start).lt("shift_slots.starts_at",range.end).order("id").range(from,to);return result as unknown as {data:Row[]|null;error:unknown;count:number|null};});
    const assignmentIds=rows.map(r=>r.id),shiftIds=[...new Set(rows.map(r=>r.shift_slot_id))];
    if(!assignmentIds.length)return{ok:true,items:[],all:[]};
    const [events,records,plans,incidents]=await Promise.all([supabase.from("attendance_events").select("assignment_id,event_type,server_received_at").in("assignment_id",assignmentIds).in("event_type",["start_work","end_work"]).order("server_received_at"),supabase.from("attendance_records").select("assignment_id").in("assignment_id",assignmentIds),supabase.from("shift_placement_plans").select("id,shift_slot_id").in("shift_slot_id",shiftIds),supabase.from("operational_incidents").select("id,assignment_id,state,category,created_at").in("assignment_id",assignmentIds).in("state",["open","acknowledged"])]);
    if(events.error||records.error||plans.error||incidents.error)throw events.error??records.error??plans.error??incidents.error;
    const planIds=(plans.data??[]).map(p=>p.id);const [positions,segments,breaks]=planIds.length?await Promise.all([supabase.from("shift_positions").select("id,label").in("plan_id",planIds).is("retired_at",null),supabase.from("assignment_placement_segments").select("assignment_id,position_id,start_at,end_at").in("plan_id",planIds).in("assignment_id",assignmentIds),supabase.from("assignment_break_intervals").select("assignment_id,start_at,end_at").in("plan_id",planIds).in("assignment_id",assignmentIds)]):[{data:[],error:null},{data:[],error:null},{data:[],error:null}];
    if(positions.error||segments.error||breaks.error)throw positions.error??segments.error??breaks.error;const positionById=new Map((positions.data??[]).map(p=>[p.id,p.label]));const confirmed=new Set((records.data??[]).map(r=>r.assignment_id));const eventMap=new Map<string,{start:string|null;end:string|null}>();for(const e of events.data??[]){const v=eventMap.get(e.assignment_id)??{start:null,end:null};if(e.event_type==="start_work"&&!v.start)v.start=e.server_received_at;if(e.event_type==="end_work"&&!v.end)v.end=e.server_received_at;eventMap.set(e.assignment_id,v);}
    const incidentByAssignment=new Map(((incidents.data??[]) as IncidentRow[]).map(i=>[i.assignment_id,{id:i.id,state:i.state,category:i.category,createdAt:i.created_at}]));
    const inputs:DayOfInput[]=rows.map(r=>{const e=eventMap.get(r.id);const preShift=Array.isArray(r.pre_shift_confirmations)?r.pre_shift_confirmations[0]:r.pre_shift_confirmations;return{assignmentId:r.id,assignmentStatus:r.status,workerId:r.worker_id,workerName:r.workers.display_name,staffCode:r.workers.staff_code,shiftId:r.shift_slot_id,startsAt:r.shift_slots.starts_at,endsAt:r.shift_slots.ends_at,requiredWorkers:r.shift_slots.required_workers,projectId:r.shift_slots.jobs.projects.id,projectName:r.shift_slots.jobs.projects.name,jobId:r.shift_slots.jobs.id,jobName:r.shift_slots.jobs.name,workplaceName:r.shift_slots.jobs.workplaces.name,startWorkAt:e?.start??null,endWorkAt:e?.end??null,preShift:preShift?{canWork:preShift.can_work,submittedAt:preShift.submitted_at}:null,placements:(segments.data??[]).filter(s=>s.assignment_id===r.id).map(s=>({position:positionById.get(s.position_id)??"終了した配置枠",startAt:s.start_at,endAt:s.end_at})),breaks:(breaks.data??[]).filter(b=>b.assignment_id===r.id).map(b=>({startAt:b.start_at,endAt:b.end_at})),attendanceConfirmed:confirmed.has(r.id),incidentAttention:incidentByAssignment.get(r.id)??null}});return{ok:true,items:buildDayOfItems(inputs,query,now),all:buildDayOfItems(inputs,{...query,q:"",project:"",state:"all",assignment:""},now)};
  }catch(error){console.error("Failed to load admin day-of monitor",error);return{ok:false as const};}
}
