import type { AttendanceDetail } from "@/lib/admin/attendance/attendance-detail-types";
import { AdminPage } from "@/components/admin/admin-page";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { AttendanceConfirmationForm } from "./attendance-confirmation-form";
import { AttendanceRevisionForm } from "./attendance-revision-form";

const dateTime = new Intl.DateTimeFormat("ja-JP", { timeZone: "Asia/Tokyo", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false });
const day = new Intl.DateTimeFormat("ja-JP", { timeZone: "Asia/Tokyo", year: "numeric", month: "2-digit", day: "2-digit" });
function localParts(value: string) { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Tokyo", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false }).formatToParts(new Date(value)); const get = (type: Intl.DateTimeFormatPartTypes) => parts.find((part) => part.type === type)?.value ?? ""; return { date: `${get("year")}-${get("month")}-${get("day")}`, time: `${get("hour")}:${get("minute")}:${get("second")}` }; }
function WorkTime({ start, end, breakMinutes }: { start: string; end: string; breakMinutes: number }) { const minutes = Math.max(Math.floor((Date.parse(end) - Date.parse(start)) / 60_000) - breakMinutes, 0); return <>{Math.floor(minutes / 60)}時間{String(minutes % 60).padStart(2, "0")}分</>; }
export function AttendanceDetailView({ detail }: { detail: AttendanceDetail }) {
  const start = detail.startWorkAt ?? detail.plannedStartAt; const end = detail.endWorkAt ?? detail.plannedEndAt; const startParts = localParts(start); const endParts = localParts(end);
  return <AdminPage><AdminPageHeader eyebrow="勤怠詳細" title={detail.workerName} description={`${detail.projectName} / ${detail.jobName} / ${detail.workplaceName}`} />
    <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-semibold">予定</h2><dl className="mt-3 grid grid-cols-[7rem_1fr] gap-2 text-sm"><dt>勤務日</dt><dd>{day.format(new Date(detail.plannedStartAt))}</dd><dt>予定勤務</dt><dd>{dateTime.format(new Date(detail.plannedStartAt))}〜{dateTime.format(new Date(detail.plannedEndAt))}</dd><dt>予定休憩</dt><dd>{detail.plannedBreakMinutes}分</dd><dt>Assignment</dt><dd>{detail.assignmentStatus}</dd></dl></section>
    <section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-semibold">Worker打刻（server_received_at）</h2><dl className="mt-3 grid grid-cols-[7rem_1fr] gap-2 text-sm"><dt>勤務開始</dt><dd>{detail.startWorkAt ? dateTime.format(new Date(detail.startWorkAt)) : "打刻なし"}</dd><dt>勤務終了</dt><dd>{detail.endWorkAt ? dateTime.format(new Date(detail.endWorkAt)) : "打刻なし"}</dd></dl>{detail.startWorkAt && !detail.endWorkAt && <p className="mt-3 rounded bg-amber-50 p-3 text-sm text-amber-900">退勤打刻がありません。管理者入力で勤務終了時刻を補正して確定できます。</p>}{!detail.startWorkAt && !detail.endWorkAt && <p className="mt-3 rounded bg-amber-50 p-3 text-sm text-amber-900">Workerの勤務開始・終了打刻がありません。管理者入力のみで勤怠を確定します。</p>}{!detail.startWorkAt && detail.endWorkAt && <p className="mt-3 rounded bg-red-50 p-3 text-sm text-red-800">開始打刻がなく終了打刻だけ存在するため、勤怠を確定できません。</p>}</section></div>
    {detail.record ? <><section className="rounded-lg border border-emerald-200 bg-white p-5"><p className="font-semibold text-emerald-800">勤怠確定済み</p><dl className="mt-3 grid grid-cols-[7rem_1fr] gap-2 text-sm"><dt>実勤務</dt><dd>{dateTime.format(new Date(detail.record.actualStartAt))}〜{dateTime.format(new Date(detail.record.actualEndAt))}</dd><dt>休憩</dt><dd>{detail.record.breakMinutes}分</dd><dt>実働</dt><dd><WorkTime start={detail.record.actualStartAt} end={detail.record.actualEndAt} breakMinutes={detail.record.breakMinutes} /></dd><dt>確定者</dt><dd>{detail.record.approvedByName}</dd><dt>確定日時</dt><dd>{dateTime.format(new Date(detail.record.approvedAt))}</dd>{detail.record.adjustmentReason && <><dt>確定時の補正理由</dt><dd>{detail.record.adjustmentReason}</dd></>}</dl><AttendanceRevisionForm assignmentId={detail.assignmentId} actualStartAt={detail.record.actualStartAt} actualEndAt={detail.record.actualEndAt} breakMinutes={detail.record.breakMinutes}/></section>
    <section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-semibold">訂正履歴</h2>{detail.revisions.length === 0 ? <p className="mt-3 text-sm text-slate-600">訂正履歴はありません。</p> : <ol className="mt-4 space-y-4">{detail.revisions.map((revision) => { const startChanged = revision.beforeActualStartAt !== revision.afterActualStartAt; const endChanged = revision.beforeActualEndAt !== revision.afterActualEndAt; const breakChanged = revision.beforeBreakMinutes !== revision.afterBreakMinutes; const beforeWork = Math.max(Math.floor((Date.parse(revision.beforeActualEndAt) - Date.parse(revision.beforeActualStartAt)) / 60000) - revision.beforeBreakMinutes, 0); const afterWork = Math.max(Math.floor((Date.parse(revision.afterActualEndAt) - Date.parse(revision.afterActualStartAt)) / 60000) - revision.afterBreakMinutes, 0); return <li key={revision.id} className="rounded border border-slate-200 p-4 text-sm"><p className="font-semibold">{revision.changedByName}・{dateTime.format(new Date(revision.changedAt))}</p><p className="mt-2 whitespace-pre-wrap text-slate-700">理由：{revision.reason}</p><dl className="mt-3 grid grid-cols-[6rem_1fr] gap-2">{startChanged && <><dt>勤務開始</dt><dd>{dateTime.format(new Date(revision.beforeActualStartAt))} → {dateTime.format(new Date(revision.afterActualStartAt))}</dd></>}{endChanged && <><dt>勤務終了</dt><dd>{dateTime.format(new Date(revision.beforeActualEndAt))} → {dateTime.format(new Date(revision.afterActualEndAt))}</dd></>}{breakChanged && <><dt>休憩</dt><dd>{revision.beforeBreakMinutes}分 → {revision.afterBreakMinutes}分</dd></>}{beforeWork !== afterWork && <><dt>実働</dt><dd>{Math.floor(beforeWork / 60)}時間{String(beforeWork % 60).padStart(2, "0")}分 → {Math.floor(afterWork / 60)}時間{String(afterWork % 60).padStart(2, "0")}分</dd></>}</dl></li>; })}</ol>}</section></> : (detail.assignmentStatus === "assigned" || detail.assignmentStatus === "confirmed") && !(detail.endWorkAt && !detail.startWorkAt) ? <AttendanceConfirmationForm initial={{ assignmentId: detail.assignmentId, actualStartDate: startParts.date, actualStartTime: startParts.time, actualEndDate: endParts.date, actualEndTime: endParts.time, breakMinutes: String(detail.plannedBreakMinutes), adjustmentReason: "" }} /> : <p className="rounded-lg border border-slate-200 bg-white p-5 text-slate-700">この勤務は勤怠確定の対象ではありません。</p>}
  </AdminPage>;
}
