"use client";

import { useActionState, useState } from "react";
import { X } from "lucide-react";
import { reviseAttendanceRecord, type AttendanceActionResult } from "@/app/actions/attendance";
import { Drawer } from "@/components/admin/drawer";
import { attendanceRevisionSchema, type AttendanceRevisionInput } from "@/lib/admin/attendance/attendance-revision-schema";

const initialState: AttendanceActionResult = { ok: true };
const field = "min-h-11 min-w-0 flex-1 rounded-control border border-border-strong bg-surface px-3 focus-visible:outline-2 focus-visible:outline-focus-ring";
function localParts(value: string) { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Tokyo", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false }).formatToParts(new Date(value)); const get = (type: Intl.DateTimeFormatPartTypes) => parts.find((part) => part.type === type)?.value ?? ""; return { date: `${get("year")}-${get("month")}-${get("day")}`, time: `${get("hour")}:${get("minute")}:${get("second")}` }; }

export function AttendanceRevisionForm({ assignmentId, actualStartAt, actualEndAt, breakMinutes }: { assignmentId: string; actualStartAt: string; actualEndAt: string; breakMinutes: number }) {
  const start = localParts(actualStartAt); const end = localParts(actualEndAt);
  const initial: AttendanceRevisionInput = { assignmentId, actualStartDate: start.date, actualStartTime: start.time, actualEndDate: end.date, actualEndTime: end.time, breakMinutes: String(breakMinutes), reason: "" };
  const [editing, setEditing] = useState(false); const [values, setValues] = useState(initial);
  const [state, action, pending] = useActionState(async (_previous: AttendanceActionResult, form: FormData) => {
    const parsed = attendanceRevisionSchema.safeParse(Object.fromEntries(form));
    if (!parsed.success) return { ok: false as const, message: parsed.error.issues[0]?.message ?? "入力内容を確認してください。" };
    if (!window.confirm("この内容で勤怠を訂正しますか？\n訂正内容と理由は監査履歴に保存されます。")) return { ok: true as const };
    const result = await reviseAttendanceRecord(parsed.data); if (result.ok) setEditing(false); return result;
  }, initialState);
  const update = (name: keyof AttendanceRevisionInput) => ({ name, value: values[name], onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setValues({ ...values, [name]: event.target.value }) });
  const close = () => { if (!pending) { setValues(initial); setEditing(false); } };
  const changes = [values.actualStartDate !== initial.actualStartDate || values.actualStartTime !== initial.actualStartTime ? "勤務開始" : "", values.actualEndDate !== initial.actualEndDate || values.actualEndTime !== initial.actualEndTime ? "勤務終了" : "", values.breakMinutes !== initial.breakMinutes ? "休憩" : ""].filter(Boolean);
  return <><button type="button" onClick={() => setEditing(true)} className="mt-5 min-h-11 rounded-control border border-border-strong px-5 font-semibold hover:bg-surface-hover focus-visible:outline-2 focus-visible:outline-focus-ring">勤怠を訂正</button><Drawer open={editing} titleId="attendance-revision-title" closeDisabled={pending} onClose={close}><header className="sticky top-0 z-10 flex items-start justify-between border-b border-border bg-surface p-4 sm:p-6"><div><h2 id="attendance-revision-title" className="text-xl font-semibold">勤怠を訂正</h2><p className="mt-1 text-sm text-foreground-muted">変更前後と理由を監査履歴へ保存します。</p></div><button autoFocus type="button" onClick={close} disabled={pending} aria-label="勤怠訂正を閉じる" className="inline-flex size-11 items-center justify-center rounded-control hover:bg-surface-hover"><X aria-hidden className="size-5" /></button></header>{editing&&<form action={action} className="space-y-5 p-4 sm:p-6"><input type="hidden" name="assignmentId" value={assignmentId} /><div className="grid gap-4 sm:grid-cols-2"><fieldset><legend className="text-sm font-semibold">実勤務開始</legend><div className="mt-1 flex gap-2"><input aria-label="訂正後開始日" type="date" required {...update("actualStartDate")} className={field}/><input aria-label="訂正後開始時刻" type="time" step="1" required {...update("actualStartTime")} className={field}/></div></fieldset><fieldset><legend className="text-sm font-semibold">実勤務終了</legend><div className="mt-1 flex gap-2"><input aria-label="訂正後終了日" type="date" required {...update("actualEndDate")} className={field}/><input aria-label="訂正後終了時刻" type="time" step="1" required {...update("actualEndTime")} className={field}/></div></fieldset></div><label className="block text-sm font-semibold">休憩（分）<input inputMode="numeric" required {...update("breakMinutes")} className={`mt-1 w-full sm:max-w-48 ${field}`}/></label><label className="block text-sm font-semibold">訂正理由（必須）<textarea required maxLength={500} rows={4} {...update("reason")} aria-invalid={!state.ok||undefined} className="mt-1 w-full rounded-control border border-border-strong bg-surface p-3"/></label><p className="rounded-control bg-surface-subtle p-3 text-sm">変更項目：{changes.length?changes.join("、"):"変更なし"}</p>{!state.ok&&<p role="alert" className="text-sm text-danger">{state.message}</p>}<div className="flex flex-col-reverse gap-3 border-t border-border pt-5 sm:flex-row sm:justify-end"><button type="button" disabled={pending} onClick={close} className="min-h-11 rounded-control border border-border-strong px-5 font-semibold">キャンセル</button><button disabled={pending} className="min-h-11 rounded-control bg-primary px-5 font-semibold text-primary-foreground disabled:bg-surface-muted">{pending?"訂正中...":"訂正を保存"}</button></div></form>}</Drawer></>;
}
