"use client";

import { X } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useRef, useState, useTransition } from "react";
import { acknowledgeOperationalIncident, resolveOperationalIncident } from "@/app/actions/operational-incidents";
import { adminStateActionClass } from "@/components/admin/admin-state";
import { Drawer } from "@/components/admin/drawer";
import type { AdminIncident, AdminIncidentEvent } from "@/lib/admin/incidents/incident-types";
import { incidentCategoryLabels } from "@/lib/worker/incidents/worker-incident-ui";

const dt=new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false});
const stateLabels={open:"未対応",acknowledged:"対応中",resolved:"解決済み",retracted:"取り下げ"} as const;
const eventLabels={created:"Workerが送信",acknowledged:"管理者が対応開始",resolved:"管理者が解決",retracted:"Workerが取り下げ"} as const;

export function IncidentDrawer({incident,events,closeHref}:{incident:AdminIncident;events:AdminIncidentEvent[];closeHref:string}){
  const router=useRouter(); const [pending,startTransition]=useTransition(); const [confirmResolve,setConfirmResolve]=useState(false); const [error,setError]=useState<string|null>(null); const key=useRef<string|null>(null);
  const close=()=>{router.push(closeHref,{scroll:false});let attempts=0;const restore=window.setInterval(()=>{attempts+=1;const trigger=document.getElementById(`incident-${incident.id}`);trigger?.focus();if(document.activeElement===trigger||attempts===10)window.clearInterval(restore);},50);};
  const mutate=(command:"acknowledge"|"resolve")=>{key.current??=crypto.randomUUID();setError(null);startTransition(async()=>{try{const action=command==="acknowledge"?acknowledgeOperationalIncident:resolveOperationalIncident;const result=await action({incidentId:incident.id,expectedVersion:incident.version,idempotencyKey:key.current!});if(result.ok){key.current=null;setConfirmResolve(false);router.refresh();}else{setError(result.message);if(result.refresh){setConfirmResolve(false);router.refresh();}else key.current=null;}}catch{setError("通信結果を確認できませんでした。同じ操作を再度お試しください。");}});};
  return <Drawer open titleId="incident-drawer-title" onClose={close} closeDisabled={pending}>
    <header className="flex items-start justify-between border-b border-border p-5 sm:p-6"><div><p className="text-sm font-medium text-link">ヘルプリクエスト</p><h2 id="incident-drawer-title" className="mt-1 text-xl font-semibold">{incident.workerName}</h2><p className="mt-1 text-sm text-foreground-muted">{incident.staffCode}・{dt.format(new Date(incident.createdAt))}</p><span className={`mt-3 inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${incident.state==="open"?"bg-warning-subtle text-warning-foreground":incident.state==="acknowledged"?"bg-info-subtle text-info-foreground":"bg-surface-muted text-foreground-secondary"}`}>{stateLabels[incident.state]}</span></div><button autoFocus type="button" disabled={pending} onClick={close} aria-label="ヘルプリクエスト詳細を閉じる" className="inline-flex size-11 items-center justify-center rounded-control hover:bg-surface-hover focus-visible:outline-2 focus-visible:outline-focus-ring disabled:text-foreground-disabled"><X aria-hidden className="size-5"/></button></header>
    <div className="space-y-6 p-5 sm:p-6">
      {error&&<p role="alert" className="rounded-panel border border-danger/30 bg-danger-subtle p-3 text-sm text-danger-foreground">{error}</p>}
      <section aria-labelledby="incident-content-heading"><h3 id="incident-content-heading" className="font-semibold">Help Request内容</h3><dl className="mt-3 grid gap-3 text-sm"><div><dt className="text-foreground-muted">カテゴリ</dt><dd className="mt-1 font-medium">{incidentCategoryLabels[incident.category]}</dd></div><div><dt className="text-foreground-muted">状況</dt><dd className="mt-1 whitespace-pre-wrap break-words">{incident.message??"補足なし"}</dd></div></dl></section>
      <section className="border-t border-border pt-6"><h3 className="font-semibold">勤務情報</h3><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-foreground-muted">案件・業務</dt><dd className="mt-1">{incident.projectName} / {incident.jobName}</dd></div><div><dt className="text-foreground-muted">勤務先</dt><dd className="mt-1">{incident.workplaceName}</dd></div><div><dt className="text-foreground-muted">予定時間</dt><dd className="mt-1">{dt.format(new Date(incident.startsAt))}–{dt.format(new Date(incident.endsAt))}</dd></div></dl></section>
      <section className="border-t border-border pt-6"><h3 className="font-semibold">対応履歴</h3><ol className="mt-3 space-y-3">{events.map(event=><li key={event.id} className="border-l-2 border-border pl-4"><p className="text-sm font-medium">{eventLabels[event.eventType]}</p><p className="mt-1 text-xs text-foreground-muted">{dt.format(new Date(event.createdAt))}・{event.actorName}・v{event.versionFrom}→v{event.versionTo}</p></li>)}</ol></section>
      <nav aria-label="関連画面" className="grid gap-2 border-t border-border pt-6 sm:grid-cols-2"><Link href={`/admin/workers/${incident.workerId}`} className={adminStateActionClass}>スタッフ詳細</Link><Link href={`/admin/shifts/${incident.shiftId}`} className={adminStateActionClass}>シフト詳細</Link><Link href={`/admin/attendance/${incident.assignmentId}`} className={adminStateActionClass}>勤怠詳細</Link><Link href={`/admin/day-of?date=${new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo"}).format(new Date(incident.startsAt))}&assignment=${incident.assignmentId}`} className={adminStateActionClass}>当日運用</Link></nav>
      {incident.state==="open"&&<button type="button" disabled={pending} onClick={()=>mutate("acknowledge")} className="min-h-12 w-full rounded-control bg-primary px-5 font-semibold text-primary-foreground disabled:bg-surface-muted">{pending?"更新中…":"対応を開始"}</button>}
      {incident.state==="acknowledged"&&!confirmResolve&&<button type="button" disabled={pending} onClick={()=>setConfirmResolve(true)} className="min-h-12 w-full rounded-control bg-primary px-5 font-semibold text-primary-foreground">解決済みにする</button>}
      {incident.state==="acknowledged"&&confirmResolve&&<section aria-labelledby="resolve-confirm-title" className="rounded-panel border border-warning/30 bg-warning-subtle p-4"><h3 id="resolve-confirm-title" className="font-semibold">このHelp Requestを解決済みにしますか？</h3><p className="mt-2 text-sm text-foreground-secondary">解決後は再開できません。対応が完了していることを確認してください。</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><button autoFocus type="button" disabled={pending} onClick={()=>mutate("resolve")} className="min-h-11 rounded-control bg-primary px-4 font-semibold text-primary-foreground">{pending?"更新中…":"解決済みにする"}</button><button type="button" disabled={pending} onClick={()=>setConfirmResolve(false)} className="min-h-11 rounded-control border border-border-strong bg-surface px-4 font-semibold">キャンセル</button></div></section>}
    </div>
  </Drawer>;
}
