import Link from "next/link";
import { adminStateActionClass } from "@/components/admin/admin-state";
import { adminIncidentHref } from "@/lib/admin/incidents/incident-rules";
import type { AdminIncident, AdminIncidentQuery } from "@/lib/admin/incidents/incident-types";
import { incidentCategoryLabels } from "@/lib/worker/incidents/worker-incident-ui";

const dt=new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false});
const labels={open:"未対応",acknowledged:"対応中",resolved:"解決済み",retracted:"取り下げ"} as const;
export function IncidentList({items,query}:{items:AdminIncident[];query:AdminIncidentQuery}){return <ul className="divide-y divide-border overflow-hidden rounded-panel border border-border bg-surface">{items.map(item=><li key={item.id} className={`grid gap-3 border-l-4 p-4 md:grid-cols-[9rem_minmax(10rem,1fr)_minmax(12rem,1.4fr)_7rem] md:items-center md:px-5 ${item.state==="open"?"border-l-warning bg-warning-subtle/25":item.state==="acknowledged"?"border-l-info bg-info-subtle/20":"border-l-transparent"}`}><div><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${item.state==="open"?"bg-warning-subtle text-warning-foreground":item.state==="acknowledged"?"bg-info-subtle text-info-foreground":"bg-surface-muted text-foreground-secondary"}`}>{labels[item.state]}</span><p className="mt-2 text-xs text-foreground-muted">{dt.format(new Date(item.createdAt))}</p></div><div><Link href={`/admin/workers/${item.workerId}`} className="font-semibold text-link hover:underline">{item.workerName}</Link><p className="mt-1 text-xs text-foreground-muted">{item.staffCode}</p><p className="mt-2 text-sm">{incidentCategoryLabels[item.category]}</p></div><div className="min-w-0"><p className="truncate text-sm text-foreground-secondary">{item.message??"補足なし"}</p><p className="mt-2 truncate text-xs text-foreground-muted">{item.projectName} / {item.jobName} / {item.workplaceName}</p><p className="mt-1 text-xs tabular-nums text-foreground-muted">{dt.format(new Date(item.startsAt))}–{dt.format(new Date(item.endsAt))}</p></div><div className="md:text-right"><Link id={`incident-${item.id}`} href={adminIncidentHref(query,{incident:item.id})} scroll={false} className={adminStateActionClass}>詳細</Link></div></li>)}</ul>}
