import Link from "next/link";
import { adminStateActionClass } from "@/components/admin/admin-state";
import { dayOfHref, operationalLabel, placementLabel, plannedBreakLabel, type DayOfItem, type DayOfQuery } from "@/lib/admin/day-of/day-of-rules";

const time = new Intl.DateTimeFormat("ja-JP", { timeZone: "Asia/Tokyo", hour: "2-digit", minute: "2-digit", hour12: false });
const stateClass = (item: DayOfItem) => item.state === "no_show" || item.state === "absent" ? "bg-danger-subtle text-danger-foreground" : item.state === "start_missing" || item.lateMinutes > 0 ? "bg-warning-subtle text-warning-foreground" : item.state === "working" ? "bg-success-subtle text-success-foreground" : "bg-surface-muted text-foreground-secondary";

export function DayOfMonitor({ items, query }: { items: DayOfItem[]; query: DayOfQuery }) {
  const groups = [...new Map(items.map((item) => [item.shiftId, { shift: item, items: items.filter((candidate) => candidate.shiftId === item.shiftId) }])).values()];
  return <div className="space-y-4">{groups.map(({ shift, items: staff }) => <section key={shift.shiftId} className="overflow-hidden rounded-panel border border-border bg-surface">
    <header className="flex flex-col gap-3 border-b border-border bg-surface-subtle px-4 py-3 sm:px-5 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-x-3 gap-y-1"><Link href={`/admin/shifts/${shift.shiftId}`} className="font-semibold text-link hover:underline">{time.format(new Date(shift.startsAt))}–{time.format(new Date(shift.endsAt))}</Link><span className="text-xs text-foreground-muted">必要 {shift.requiredWorkers}名 / 勤務予定 {staff.length}名</span></div><p className="mt-1 truncate text-sm"><Link href={`/admin/projects/${shift.projectId}`} className="font-medium text-link hover:underline">{shift.projectName}</Link><span className="text-foreground-secondary"> / {shift.jobName} / {shift.workplaceName}</span></p></div><Link href={`/admin/placement?date=${query.date}&shift=${shift.shiftId}`} className={adminStateActionClass}>配置・休憩を確認</Link></header>
    <div className="hidden grid-cols-[minmax(10rem,1.2fr)_7rem_minmax(9rem,1fr)_minmax(10rem,1.1fr)_minmax(9rem,1fr)_5rem] gap-4 border-b border-border px-5 py-2.5 text-xs font-semibold text-foreground-muted md:grid"><span>スタッフ</span><span>勤務時間</span><span>勤務状態</span><span>配置・前日確認</span><span>要確認</span><span className="text-right">詳細</span></div>
    <ul className="divide-y divide-border">{staff.map((item) => { const placement = placementLabel(item, query.date); const strong = item.state === "no_show" || item.state === "absent"; return <li key={item.assignmentId} className={`grid gap-3 border-l-4 p-4 md:grid-cols-[minmax(10rem,1.2fr)_7rem_minmax(9rem,1fr)_minmax(10rem,1.1fr)_minmax(9rem,1fr)_5rem] md:items-center md:px-4 ${item.attentionReason ? strong ? "border-l-danger bg-danger-subtle/30" : "border-l-warning bg-warning-subtle/30" : "border-l-transparent"}`}>
      <div><Link href={`/admin/workers/${item.workerId}`} className="font-semibold text-link hover:underline">{item.workerName}</Link><p className="mt-1 text-xs text-foreground-muted">{item.staffCode}</p></div>
      <div><p className="mb-1 text-xs font-medium text-foreground-muted md:hidden">勤務時間</p><p className="text-sm tabular-nums">{time.format(new Date(item.startsAt))}–{time.format(new Date(item.endsAt))}</p></div>
      <div><p className="mb-1 text-xs font-medium text-foreground-muted md:hidden">勤務状態</p><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${stateClass(item)}`}>{operationalLabel(item)}</span></div>
      <div className="space-y-1 text-sm"><p className="mb-1 text-xs font-medium text-foreground-muted md:hidden">配置・前日確認</p><p>{placement.value ? `${placement.prefix}：${placement.value}` : "配置設定なし"}</p><p className="text-foreground-secondary">{item.breaks.length ? `${plannedBreakLabel(item, query.date)} ${time.format(new Date(item.breaks[0].startAt))}–${time.format(new Date(item.breaks[0].endAt))}` : "予定休憩なし"}</p><p className="text-xs text-foreground-muted">前日確認：{item.preShift ? item.preShift.canWork ? "提出済み" : "勤務不可回答" : "未提出"}</p></div>
      <div><p className="mb-1 text-xs font-medium text-foreground-muted md:hidden">要確認</p>{item.attentionReason ? <p className={`text-sm font-semibold ${strong ? "text-danger-foreground" : "text-warning-foreground"}`}>{item.attentionReason}</p> : <p className="text-sm text-foreground-muted">なし</p>}</div>
      <div className="md:text-right"><Link id={`assignment-${item.assignmentId}`} href={dayOfHref(query, { assignment: item.assignmentId })} scroll={false} className={adminStateActionClass}>詳細</Link></div>
    </li>; })}</ul>
  </section>)}</div>;
}
