import Link from "next/link";
import { AdminPage } from "@/components/admin/admin-page";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { AdminSectionNav } from "@/components/admin/admin-section-nav";
import { AdminEmptyState, AdminErrorState, AdminNotFoundState, adminStateActionClass } from "@/components/admin/admin-state";
import { PreShiftMonitor } from "@/components/admin/pre-shift/pre-shift-monitor";
import { PreShiftDrawer } from "@/components/admin/pre-shift/pre-shift-drawer";
import { getPreShiftMonitor } from "@/lib/admin/pre-shift/get-pre-shift-monitor";
import { filterPreShiftItems, parsePreShiftQuery, preShiftHref } from "@/lib/admin/pre-shift/pre-shift-rules";
import { addDays, shiftDayLabel, tokyoDate } from "@/lib/admin/shifts/shift-view-rules";
const control="mt-1.5 min-h-11 w-full rounded-control border border-border-strong bg-surface px-3 text-sm focus-visible:outline-2 focus-visible:outline-focus-ring";
export default async function PreShiftPage({searchParams}:PageProps<"/admin/pre-shift">){const raw=await searchParams;const query=parsePreShiftQuery(raw);const result=await getPreShiftMonitor(query.date);const items=result.ok?filterPreShiftItems(result.items,query):[];const projects=result.ok?[...new Map(result.items.map(i=>[i.projectId,i.projectName])).entries()].sort((a,b)=>a[1].localeCompare(b[1],"ja")):[];const selected=result.ok?result.items.find(i=>i.assignmentId===query.assignment):undefined;const closeHref=preShiftHref(query,{assignment:""});const confirmed=result.ok?result.items.filter(i=>i.confirmation).length:0;const pending=result.ok?result.items.length-confirmed:0;const shifts=result.ok?new Set(result.items.map(i=>i.shiftId)).size:0;const filtered=Boolean(query.q||query.project||query.status!=="all");
return <AdminPage><AdminPageHeader title="前日確認" description="勤務日前の確認状況を、スタッフ単位で確認します。" actions={<><Link href={preShiftHref(query,{date:addDays(query.date,-1),assignment:""})} className={adminStateActionClass}>前日</Link><span className="px-2 text-sm font-semibold">{shiftDayLabel(query.date)}</span><Link href={preShiftHref(query,{date:addDays(query.date,1),assignment:""})} className={adminStateActionClass}>翌日</Link></>}/><AdminSectionNav label="案件・運用" items={[{label:"案件",href:"/admin/projects"},{label:"シフト",href:"/admin/shifts"},{label:"前日確認",href:"/admin/pre-shift",current:true}]}/>
{result.ok&&<section aria-label="集計" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["対象シフト",shifts],["対象スタッフ",result.items.length],["確認済み",confirmed],["未確認",pending]].map(([label,value])=><div key={label} className="rounded-panel border border-border bg-surface p-4"><p className="text-sm text-foreground-muted">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</section>}
<form method="get" className="rounded-panel border border-border bg-surface p-4"><input type="hidden" name="date" value={query.date}/><div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-medium">検索<input name="q" type="search" defaultValue={query.q} placeholder="スタッフ・案件" maxLength={100} className={control}/></label><label className="text-sm font-medium">案件<select name="project" defaultValue={query.project} className={control}><option value="">すべて</option>{projects.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label className="text-sm font-medium">確認状態<select name="status" defaultValue={query.status} className={control}><option value="all">すべて</option><option value="pending">未確認</option><option value="confirmed">確認済み</option></select></label></div><div className="mt-4 flex flex-wrap justify-end gap-3"><Link href={`/admin/pre-shift?date=${query.date}`} className={adminStateActionClass}>条件をリセット</Link><button className="min-h-11 rounded-control bg-primary px-5 text-sm font-semibold text-primary-foreground">検索</button></div></form>
{!result.ok?<AdminErrorState title="前日確認を取得できませんでした。"/>:result.items.length===0?<AdminEmptyState title="この日の配置はありません。" description="前後の日付を選択してください。"/>:items.length===0?<AdminEmptyState title="条件に一致するスタッフはいません。" description="検索条件を変更してください。"/>:<><PreShiftMonitor items={items} query={query}/>{pending===0&&!filtered&&<AdminEmptyState title="全員の前日確認が完了しています。" description="未確認のスタッフはいません。"/>}</>}
{query.assignment&&(selected?<PreShiftDrawer item={selected} closeHref={closeHref}/>:<div className="fixed inset-0 z-50 grid place-items-center bg-[var(--surface-overlay)] p-4"><AdminNotFoundState><Link href={closeHref} className={adminStateActionClass}>一覧へ戻る</Link></AdminNotFoundState></div>)}
<div className="flex justify-end"><Link href={`/admin/pre-shift?date=${addDays(tokyoDate(new Date()),1)}`} className="text-sm font-medium text-link hover:underline">明日を表示</Link></div></AdminPage>}
