import Link from "next/link";
import { AdminPage } from "@/components/admin/admin-page";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { AdminSectionNav } from "@/components/admin/admin-section-nav";
import { WorkerStatusBadge } from "./worker-status-badge";
import { WorkerEditor } from "./worker-editor";
import { WORKER_HISTORY_PAGE_SIZE,workerDetailHref,type WorkerTab } from "@/lib/admin/workers/worker-rules";
import type { WorkerDetail } from "@/lib/admin/workers/worker-types";
const date=new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"});const dateTime=new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false});
export function WorkerDetailView({detail,tab,historyPage,canEdit}:{detail:WorkerDetail;tab:WorkerTab;historyPage:number;canEdit:boolean}){const tabs=[{label:"概要",href:workerDetailHref(detail.id,"overview"),current:tab==="overview"},{label:"勤務履歴",href:workerDetailHref(detail.id,"history"),current:tab==="history"},{label:"基本情報",href:workerDetailHref(detail.id,"profile"),current:tab==="profile"}];return <AdminPage><AdminPageHeader eyebrow={<Link href="/admin/workers" className="hover:underline">スタッフ / {detail.displayName}</Link>} title={detail.displayName} description={`ID: ${detail.staffCode} ・ ${detail.branchName}`} actions={<div className="flex items-center gap-3"><WorkerStatusBadge status={detail.status}/>{canEdit&&<WorkerEditor worker={detail}/>}</div>}/><AdminSectionNav label="スタッフ詳細" items={tabs}/>{tab==="overview"&&<Overview detail={detail}/>} {tab==="history"&&<History detail={detail} page={historyPage}/>} {tab==="profile"&&<Profile detail={detail}/>}</AdminPage>}
function Overview({detail}:{detail:WorkerDetail}){return <><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="次回勤務" value={detail.nextWork?dateTime.format(new Date(detail.nextWork.startsAt)):"—"}/><Metric label="直近勤務" value={detail.recentWork?dateTime.format(new Date(detail.recentWork.startsAt)):"—"}/><Metric label="完了勤務" value={`${detail.totalCompleted}回`}/><Metric label="欠勤" value={`${detail.absentCount}回`}/><Metric label="無断欠勤" value={`${detail.noShowCount}回`}/></section><section className="rounded-panel border border-border bg-surface p-5"><h2 className="text-lg font-semibold">Staff Basic</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-[8rem_1fr]"><dt className="text-foreground-muted">所属</dt><dd>{detail.branchName}</dd><dt className="text-foreground-muted">状態</dt><dd><WorkerStatusBadge status={detail.status}/></dd><dt className="text-foreground-muted">Auth連携</dt><dd>{detail.authLinked?"連携済み":"未連携"}</dd></dl></section></>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-panel border border-border bg-surface p-4"><p className="text-xs text-foreground-muted">{label}</p><p className="mt-2 text-lg font-semibold">{value}</p></div>}
function History({detail,page}:{detail:WorkerDetail;page:number}){const pages=Math.max(1,Math.ceil(detail.historyTotal/WORKER_HISTORY_PAGE_SIZE));return <section><div className="mb-3 flex items-end justify-between"><div><h2 className="text-lg font-semibold">勤務履歴</h2><p className="text-sm text-foreground-muted">Assignmentを勤務日の新しい順で表示</p></div><span className="text-sm text-foreground-muted">{detail.historyTotal}件</span></div>{detail.history.length?<><ul className="space-y-3">{detail.history.map(item=><li key={item.assignmentId} className="rounded-panel border border-border bg-surface p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="font-semibold">{dateTime.format(new Date(item.startsAt))}–{dateTime.format(new Date(item.endsAt))}</p><p className="mt-1 text-sm text-foreground-secondary"><Link className="text-link hover:underline" href={`/admin/projects/${item.projectId}`}>{item.projectName}</Link> / {item.jobName} / {item.workplaceName}</p><p className="mt-1 text-xs text-foreground-muted">配置状態: {item.assignmentStatus}{item.attendance?` / 勤怠: ${item.attendance.status}`:" / 勤怠なし"}</p></div><div className="flex flex-wrap gap-3"><Link className="inline-flex min-h-11 items-center text-sm font-medium text-link" href={`/admin/shifts/${item.shiftId}`}>シフト</Link><Link className="inline-flex min-h-11 items-center text-sm font-medium text-link" href={`/admin/attendance/${item.assignmentId}`}>勤怠</Link></div></div></li>)}</ul>{pages>1&&<nav aria-label="勤務履歴ページ" className="mt-4 flex items-center justify-between">{page<=1?<span aria-disabled className="min-h-11 px-4 py-3 text-sm opacity-50">前へ</span>:<Link className="min-h-11 px-4 py-3 text-sm text-link" href={workerDetailHref(detail.id,"history",page-1)}>前へ</Link>}<span className="text-sm">{page} / {pages}</span>{page>=pages?<span aria-disabled className="min-h-11 px-4 py-3 text-sm opacity-50">次へ</span>:<Link className="min-h-11 px-4 py-3 text-sm text-link" href={workerDetailHref(detail.id,"history",page+1)}>次へ</Link>}</nav>}</>:<p className="rounded-panel border border-border bg-surface p-6 text-sm text-foreground-secondary">勤務履歴はありません。</p>}</section>}
function Profile({detail}:{detail:WorkerDetail}){return <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-panel border border-border bg-surface p-5"><h2 className="text-lg font-semibold">基本情報</h2><dl className="mt-5 grid grid-cols-[7rem_1fr] gap-4 text-sm"><dt className="text-foreground-muted">スタッフID</dt><dd>{detail.staffCode}</dd><dt className="text-foreground-muted">氏名</dt><dd>{detail.displayName}</dd><dt className="text-foreground-muted">所属</dt><dd>{detail.branchName}</dd><dt className="text-foreground-muted">状態</dt><dd><WorkerStatusBadge status={detail.status}/></dd><dt className="text-foreground-muted">登録日</dt><dd>{date.format(new Date(detail.createdAt))}</dd></dl></div><div className="rounded-panel border border-border bg-surface p-5"><h2 className="text-lg font-semibold">アカウント連携</h2><p className="mt-4 text-sm text-foreground-secondary">{detail.authLinked?`Auth/Profile連携済み${detail.profileActive===false?"（Profile停止中）":""}`:"Auth/Profile未連携"}</p><p className="mt-3 text-sm text-foreground-muted">メール・電話・カナは現行Staff Domainに保存領域がないため表示しません。</p></div></section>}
