import { Info } from "lucide-react";
import type { AvailabilityKind, WorkerAvailabilityData } from "@/lib/worker/availability/types";

const kindMeta: Record<AvailabilityKind, { symbol: string; label: string; tone: string }> = {
  available: { symbol: "○", label: "勤務可能", tone: "text-success" },
  consultable: { symbol: "△", label: "相談可能", tone: "text-warning" },
  unavailable: { symbol: "×", label: "勤務不可", tone: "text-danger" },
};
const weekdayLabels = ["月", "火", "水", "木", "金", "土", "日"];
const dateTime = new Intl.DateTimeFormat("ja-JP", { timeZone: "Asia/Tokyo", year: "numeric", month: "2-digit", day: "2-digit", weekday: "short", hour: "2-digit", minute: "2-digit", hour12: false });

export function WorkerAvailabilityReadonly({ data }: { data: WorkerAvailabilityData }) {
  const conditions = data.workConditions;
  return <div className="space-y-4"><div><h2 className="text-lg font-semibold">勤務条件</h2><p className="mt-1 text-sm text-foreground-muted">スタッフ本人が設定した勤務可能時間と希望条件です。管理者は閲覧のみできます。</p></div><section aria-labelledby="admin-availability-title" className="rounded-panel border border-border bg-surface p-5"><h3 id="admin-availability-title" className="font-semibold">勤務可能時間</h3><p className="mt-1 text-xs text-foreground-muted">登録がない時間は「不明」です。勤務可能として扱いません。</p>{data.intervals.length ? <ul className="mt-4 grid gap-3 lg:grid-cols-2">{data.intervals.map(interval => <li key={interval.id} className="rounded-control bg-surface-subtle p-4"><p className={`font-semibold ${kindMeta[interval.kind].tone}`}><span aria-hidden>{kindMeta[interval.kind].symbol}</span> {kindMeta[interval.kind].label}</p><p className="mt-1 text-sm text-foreground-secondary">{dateTime.format(new Date(interval.startsAt))} ～ {dateTime.format(new Date(interval.endsAt))}</p></li>)}</ul> : <p className="mt-4 rounded-control bg-surface-subtle p-4 text-sm text-foreground-secondary">登録なし（不明）</p>}</section><section aria-labelledby="admin-conditions-title" className="rounded-panel border border-border bg-surface p-5"><div className="flex items-start gap-2"><Info aria-hidden className="mt-0.5 size-4 shrink-0 text-info"/><div><h3 id="admin-conditions-title" className="font-semibold">希望条件</h3><p className="mt-1 text-xs text-foreground-muted">すべて参考情報です。Candidateのhard eligibilityには使用しません。</p></div></div>{conditions?.isActive ? <dl className="mt-5 grid gap-x-6 gap-y-4 text-sm sm:grid-cols-[9rem_1fr]"><dt className="text-foreground-muted">希望曜日</dt><dd>{conditions.preferredIsoWeekdays.length ? conditions.preferredIsoWeekdays.map(day => weekdayLabels[day - 1]).join("・") : "設定なし"}</dd><dt className="text-foreground-muted">希望時間</dt><dd>{conditions.preferredStartLocal && conditions.preferredEndLocal ? `${conditions.preferredStartLocal}–${conditions.preferredEndLocal}${conditions.preferredEndsNextDay ? "（翌日）" : ""}` : "設定なし"}</dd><dt className="text-foreground-muted">希望エリア</dt><dd className="whitespace-pre-wrap break-words">{conditions.preferredAreaNote ?? "設定なし"}</dd><dt className="text-foreground-muted">希望業務</dt><dd className="whitespace-pre-wrap break-words">{conditions.preferredWorkCategoryNote ?? "設定なし"}</dd><dt className="text-foreground-muted">交通手段</dt><dd className="whitespace-pre-wrap break-words">{conditions.transportPreferenceNote ?? "設定なし"}</dd></dl> : <p className="mt-4 rounded-control bg-surface-subtle p-4 text-sm text-foreground-secondary">希望条件は設定されていません。</p>}</section><aside className="rounded-control border border-border bg-surface-subtle p-4"><p className="text-sm font-semibold">情報の所有</p><p className="mt-1 text-sm text-foreground-muted">勤務可能時間・希望条件はスタッフ本人が更新します。管理者向けの変更操作は提供していません。</p></aside></div>;
}
