import Link from "next/link";
import { WorkerAnnouncementDetail } from "@/components/worker/announcements/worker-announcement-detail";
import { requireWorker } from "@/lib/auth/require-worker";
import { getWorkerAnnouncement } from "@/lib/worker/announcements/get-worker-announcements";
import { uuidSchema } from "@/lib/utils/uuid-schema";

function unavailable(){return <main className="mx-auto max-w-3xl px-4 py-8 sm:px-6"><section className="rounded-card border border-border bg-surface p-5"><h1 className="font-semibold">このお知らせは表示できません</h1><p className="mt-1 text-sm text-foreground-secondary">URLを確認するか、お知らせ一覧へ戻ってください。</p><Link href="/worker/announcements" className="mt-4 inline-flex min-h-11 items-center rounded-control font-semibold text-link focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus-ring">お知らせ一覧へ戻る</Link></section></main>;}

export default async function WorkerAnnouncementDetailPage({params}:PageProps<"/worker/announcements/[announcementId]">){await requireWorker();const parsed=uuidSchema.safeParse((await params).announcementId);if(!parsed.success)return unavailable();let result:Awaited<ReturnType<typeof getWorkerAnnouncement>>|null=null;try{result=await getWorkerAnnouncement(parsed.data);}catch(error:unknown){console.error("Failed to load Worker Announcement detail",error);}if(!result)return <main className="mx-auto max-w-3xl px-4 py-8 sm:px-6"><section role="alert" className="rounded-card border border-danger/25 bg-surface p-5"><h1 className="font-semibold">お知らせを取得できませんでした</h1><p className="mt-1 text-sm text-foreground-secondary">時間をおいて、もう一度お試しください。</p><Link href={`/worker/announcements/${parsed.data}`} className="mt-4 inline-flex min-h-11 items-center rounded-control font-semibold text-link focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus-ring">再読み込み</Link></section></main>;if(!result.ok)return unavailable();return <WorkerAnnouncementDetail announcement={result.announcement}/>;}
