import Link from "next/link";
import { ChevronRight, Megaphone } from "lucide-react";
import { WorkerAnnouncementImportance } from "./worker-announcement-importance";
import { workerAnnouncementPageUrl } from "@/lib/worker/announcements/worker-announcement-query";
import type { WorkerAnnouncementPage } from "@/lib/worker/announcements/worker-announcement-types";

const date=new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false});

export function WorkerAnnouncementList({page}:{page:WorkerAnnouncementPage}){if(page.announcements.length===0)return <section className="mt-6 rounded-card border border-border bg-surface px-5 py-10 text-center"><Megaphone aria-hidden className="mx-auto size-7 text-foreground-muted"/><h2 className="mt-3 font-semibold">現在のお知らせはありません</h2><p className="mt-1 text-sm text-foreground-muted">公開されたお知らせがここに表示されます。</p></section>;return <><ul aria-label="お知らせ一覧" className="mt-6 overflow-hidden rounded-card border border-border bg-surface">{page.announcements.map(item=><li key={item.id} className="border-b border-border last:border-b-0"><Link href={`/worker/announcements/${item.id}`} className="group flex min-h-24 items-start gap-3 px-4 py-4 hover:bg-surface-hover focus-visible:outline-2 focus-visible:-outline-offset-2 focus-visible:outline-focus-ring sm:px-5"><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><span className="break-words font-semibold">{item.title}</span><WorkerAnnouncementImportance important={item.importance==="important"}/></span><time dateTime={item.publishedAt} className="mt-2 block text-sm text-foreground-muted">公開 {date.format(new Date(item.publishedAt))}</time></span><ChevronRight aria-hidden className="mt-1 size-5 shrink-0 text-foreground-muted group-hover:text-foreground"/></Link></li>)}</ul>{page.nextCursor&&<div className="mt-5 text-center"><Link href={workerAnnouncementPageUrl(page.nextCursor)} className="inline-flex min-h-11 items-center justify-center rounded-control border border-border-strong bg-surface px-5 text-sm font-semibold hover:bg-surface-hover focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus-ring">もっと見る</Link></div>}</>;}
