"use client";
import { X } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Drawer } from "@/components/admin/drawer";
import type { PreShiftItem } from "@/lib/admin/pre-shift/pre-shift-rules";

const dateTime = new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false});
const health={good:"良好",concern:"気になる点あり",unwell:"不調"} as const;
export function PreShiftDrawer({item,closeHref}:{item:PreShiftItem;closeHref:string}) { const router=useRouter(); const close=()=>{ router.push(closeHref,{scroll:false}); setTimeout(()=>document.getElementById(`assignment-${item.assignmentId}`)?.focus(),150); }; const c=item.confirmation;
  return <Drawer open titleId="pre-shift-drawer-title" onClose={close}><div className="flex items-start justify-between border-b border-border p-5 sm:p-6"><div><p className="text-sm font-medium text-link">前日確認</p><h2 id="pre-shift-drawer-title" className="mt-1 text-xl font-semibold">{item.workerName}</h2></div><button autoFocus type="button" onClick={close} aria-label="詳細を閉じる" className="inline-flex size-11 items-center justify-center rounded-control hover:bg-surface-hover focus-visible:outline-2 focus-visible:outline-focus-ring"><X aria-hidden className="size-5"/></button></div><div className="space-y-6 p-5 sm:p-6">
    <section><h3 className="font-semibold">勤務情報</h3><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-foreground-muted">案件</dt><dd className="mt-1 font-medium">{item.projectName}</dd></div><div><dt className="text-foreground-muted">業務</dt><dd className="mt-1">{item.jobName}</dd></div><div><dt className="text-foreground-muted">勤務先</dt><dd className="mt-1">{item.workplaceName}</dd></div><div><dt className="text-foreground-muted">勤務時間</dt><dd className="mt-1">{dateTime.format(new Date(item.startsAt))}〜{dateTime.format(new Date(item.endsAt))}</dd></div></dl></section>
    <section className="border-t border-border pt-6"><h3 className="font-semibold">前日確認回答</h3>{!c?<p className="mt-3 rounded-control bg-warning-subtle p-4 text-sm">まだ提出されていません。</p>:<dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-foreground-muted">勤務可否</dt><dd className="mt-1 font-medium">{c.canWork?"勤務できます":"勤務できません"}</dd></div><div><dt className="text-foreground-muted">体調</dt><dd className="mt-1">{health[c.healthStatus]}</dd></div><div><dt className="text-foreground-muted">起床予定</dt><dd className="mt-1">{c.plannedWakeAt?dateTime.format(new Date(c.plannedWakeAt)):"-"}</dd></div><div><dt className="text-foreground-muted">出発予定</dt><dd className="mt-1">{c.plannedDepartureAt?dateTime.format(new Date(c.plannedDepartureAt)):"-"}</dd></div><div className="sm:col-span-2"><dt className="text-foreground-muted">コメント</dt><dd className="mt-1 whitespace-pre-wrap">{c.comment||"-"}</dd></div><div><dt className="text-foreground-muted">提出日時</dt><dd className="mt-1">{dateTime.format(new Date(c.submittedAt))}</dd></div><div><dt className="text-foreground-muted">更新日時</dt><dd className="mt-1">{dateTime.format(new Date(c.updatedAt))}</dd></div></dl>}</section>
    <Link href={`/admin/workers/${item.workerId}`} className="inline-flex min-h-11 items-center text-sm font-medium text-link hover:underline">スタッフ詳細を開く</Link>
  </div></Drawer>; }
