import Link from "next/link";
import type { RecruitmentShift } from "@/lib/worker/recruitment/get-worker-recruitment";

const date = new Intl.DateTimeFormat("ja-JP", { timeZone: "Asia/Tokyo", month: "numeric", day: "numeric", weekday: "short" });
const time = new Intl.DateTimeFormat("ja-JP", { timeZone: "Asia/Tokyo", hour: "2-digit", minute: "2-digit", hour12: false });
const status: Record<RecruitmentShift["state"], string> = { available: "応募できます", available_with_warning: "確認して応募できます", not_eligible: "現在は応募できません", applied: "応募済み", accepted_waiting_assignment: "採用済み・配置待ち", rejected: "今回は見送り", withdrawn: "取下げ済み", capacity_full: "定員に達しました", deadline_passed: "応募期限を過ぎました" };
const reason: Record<string, string> = { required_conditions_not_met: "必要な資格・スキルを満たしていません", other_scheduled_shift_overlaps: "ほかの予定勤務と時間が重なっています", availability_unavailable: "この時間は勤務不可として登録されています", availability_needs_confirmation: "勤務可否の確認が必要です", preference_not_matched: "登録した希望条件とは一致しません" };

function pay(item: RecruitmentShift) { const values = [item.hourlyWage == null ? null : `時給 ${item.hourlyWage.toLocaleString("ja-JP")}円`, item.transportationFeeCap == null ? null : `交通費 上限${item.transportationFeeCap.toLocaleString("ja-JP")}円`].filter(Boolean); return values.join(" / ") || "条件は詳細で確認"; }
function safeUrl(value: string | null) { if (!value) return null; try { const url = new URL(value); return url.protocol === "https:" || url.protocol === "http:" ? url.toString() : null; } catch { return null; } }

export function WorkerRecruitmentList({ items, hasMore, page }: { items: RecruitmentShift[]; hasMore: boolean; page: number }) {
  return <main className="mx-auto max-w-3xl px-4 py-6 sm:px-6 sm:py-10"><header><p className="text-sm font-semibold text-blue-700">募集中の勤務</p><h1 className="mt-2 text-2xl font-semibold text-slate-950">勤務を探す</h1><p className="mt-2 text-sm text-slate-600">応募できない勤務も、理由を確認できます。</p></header>{items.length === 0 ? <p className="mt-6 rounded-xl border border-slate-200 bg-white p-6 text-slate-600">現在募集中の勤務はありません。</p> : <ul className="mt-6 space-y-4">{items.map((item) => <li key={item.shiftId} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><p className="text-sm font-semibold text-blue-700">{item.projectName}</p><h2 className="mt-1 text-lg font-semibold text-slate-950">{item.jobName}</h2><p className="mt-3 font-semibold text-slate-900">{date.format(new Date(item.startsAt))} {time.format(new Date(item.startsAt))}〜{time.format(new Date(item.endsAt))}</p><p className="mt-1 text-sm text-slate-700">{item.workplaceName}{item.meetingAt ? ` / 集合 ${time.format(new Date(item.meetingAt))}` : ""}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold text-slate-800">{status[item.state]}</span></div><p className="mt-4 text-sm text-slate-700">{pay(item)}</p><p className="mt-1 text-sm text-slate-600">応募期限: {date.format(new Date(item.applicationDeadline))} {time.format(new Date(item.applicationDeadline))} / 残り {item.remainingCapacity} 人</p>{item.eligibility.safeReasons.length > 0 && <p className="mt-3 text-sm text-amber-800">{item.eligibility.safeReasons.map((value) => reason[value]).filter(Boolean).join("。")}</p>}<Link href={`/worker/recruitment/${item.shiftId}`} className="mt-5 inline-flex min-h-11 items-center justify-center rounded-lg bg-blue-700 px-5 text-sm font-semibold text-white hover:bg-blue-800 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600">詳細を見る</Link></li>)}</ul>}{(page > 0 || hasMore) && <nav aria-label="ページ送り" className="mt-6 flex justify-between gap-3">{page > 0 ? <Link href={`/worker/recruitment?page=${page - 1}`} className="min-h-11 rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">前へ</Link> : <span />}{hasMore && <Link href={`/worker/recruitment?page=${page + 1}`} className="min-h-11 rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">次へ</Link>}</nav>}</main>;
}

export function WorkerRecruitmentDetail({ item }: { item: RecruitmentShift }) {
  const manual = safeUrl(item.manualUrl); const map = safeUrl(item.mapUrl);
  return <main className="mx-auto max-w-3xl space-y-6 px-4 py-6 sm:px-6 sm:py-10"><Link href="/worker/recruitment" className="inline-flex min-h-11 items-center text-sm font-semibold text-blue-700 underline underline-offset-2">募集中の勤務へ戻る</Link><header><p className="text-sm font-semibold text-blue-700">{item.projectName}</p><h1 className="mt-2 text-2xl font-semibold text-slate-950">{item.jobName}</h1><p className="mt-3 font-semibold text-slate-900">{date.format(new Date(item.startsAt))} {time.format(new Date(item.startsAt))}〜{time.format(new Date(item.endsAt))}</p></header><section className="rounded-xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="text-lg font-semibold">応募状況</h2><p className="mt-3 font-semibold text-slate-900">{status[item.state]}</p>{item.eligibility.safeReasons.map((value) => <p key={value} className="mt-2 text-sm text-slate-700">{reason[value]}</p>)}<p className="mt-3 text-sm text-slate-600">応募期限: {date.format(new Date(item.applicationDeadline))} {time.format(new Date(item.applicationDeadline))} / 現在の残り枠: {item.remainingCapacity} 人</p><button disabled className="mt-5 min-h-11 rounded-lg bg-slate-200 px-5 text-sm font-semibold text-slate-600" title="応募は次のフェーズで提供予定です">応募機能は準備中です</button></section><section className="rounded-xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="text-lg font-semibold">勤務情報</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2"><Item label="勤務地">{item.workplaceName}<br />{item.workplaceAddress}</Item>{item.meetingAt && <Item label="集合時刻">{date.format(new Date(item.meetingAt))} {time.format(new Date(item.meetingAt))}</Item>}{item.meetingNote && <Item label="集合案内">{item.meetingNote}</Item>}{item.accessNote && <Item label="アクセス">{item.accessNote}</Item>}{item.description && <Item label="仕事内容">{item.description}</Item>}{item.clothingNote && <Item label="服装">{item.clothingNote}</Item>}{item.belongingsNote && <Item label="持ち物">{item.belongingsNote}</Item>}{item.mealNotes && <Item label="食事">{item.mealNotes}</Item>}{item.recruitmentNotes && <Item label="募集補足">{item.recruitmentNotes}</Item>}{manual && <Item label="業務資料"><a className="text-blue-700 underline" href={manual} target="_blank" rel="noreferrer">業務資料を開く</a></Item>}{map && <Item label="地図"><a className="text-blue-700 underline" href={map} target="_blank" rel="noreferrer">地図を開く</a></Item>}</dl></section><section className="rounded-xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="text-lg font-semibold">条件・報酬</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2"><Item label="時給">{item.hourlyWage == null ? "未設定" : `${item.hourlyWage.toLocaleString("ja-JP")}円`}</Item><Item label="交通費">{item.transportationFeeCap == null ? "未設定" : `上限${item.transportationFeeCap.toLocaleString("ja-JP")}円`}</Item>{item.requirementsText && <Item label="応募条件">{item.requirementsText}</Item>}{item.requirements.length > 0 && <Item label="必要な資格・スキル">{item.requirements.map((r) => r.name).join("、")}</Item>}</dl></section></main>;
}
function Item({ label, children }: { label: string; children: React.ReactNode }) { return <div><dt className="text-xs font-semibold text-slate-500">{label}</dt><dd className="mt-1 whitespace-pre-wrap text-slate-900">{children}</dd></div>; }
