"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useRef, useState, useTransition } from "react";
import { sendAttentionReminder, sendAttentionReminders, type AttentionReminderOutcome, type AttentionReminderResult } from "@/app/actions/attention-reminders";
import type { AttentionItem } from "@/lib/admin/attention/attention-types";

const typeLabel:Record<AttentionItem["type"],string>={staffing_shortage:"人員",placement_conflict:"Coverage",pre_confirmation_overdue:"前日確認",day_of_arrival:"当日",open_sos:"SOS",attendance_needs_review:"勤怠"};
const severityLabel={critical:"緊急",high:"高",medium:"中"} as const;
const severityClass={critical:"bg-danger-subtle text-danger",high:"bg-warning-subtle text-warning-foreground",medium:"bg-info-subtle text-info-foreground"} as const;
const outcomeLabel:Record<AttentionReminderOutcome,string>={projected:"通知を作成",not_eligible:"対象外",no_recipient:"通知先なし",inactive_recipient:"通知先なし",rate_limited:"再通知間隔内",unavailable:"対象を確認できません"};
const dateTime=new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false});
type PreConfirmationItem=Extract<AttentionItem,{type:"pre_confirmation_overdue"}>;
type Feedback={result:AttentionReminderResult;targets:Map<string,string>};

export function AttentionQueue({items}:{items:AttentionItem[]}){
  const router=useRouter();
  const eligible=items.filter((item):item is PreConfirmationItem=>item.type==="pre_confirmation_overdue"&&Boolean(item.assignmentId));
  const[selected,setSelected]=useState<Set<string>>(new Set());
  const[feedback,setFeedback]=useState<Feedback|null>(null);
  const[pending,startTransition]=useTransition();
  const operation=useRef<{snapshot:string;key:string}|null>(null);
  function toggle(assignmentId:string){setSelected(current=>{const next=new Set(current);if(next.has(assignmentId))next.delete(assignmentId);else if(next.size<50)next.add(assignmentId);return next;});setFeedback(null);}
  function execute(targets:PreConfirmationItem[]){
    if(pending||targets.length===0||targets.length>50)return;
    const ids=targets.map(item=>item.assignmentId).filter((id):id is string=>Boolean(id)).sort();
    const mode=ids.length===1?"single":"bulk";const snapshot=`${mode}:${ids.join(",")}`;
    if(operation.current?.snapshot!==snapshot)operation.current={snapshot,key:crypto.randomUUID()};
    const key=operation.current.key;const targetMap=new Map(targets.map(item=>[item.assignmentId!,item.target]));setFeedback(null);
    startTransition(async()=>{try{const result=mode==="single"?await sendAttentionReminder({assignmentId:ids[0],idempotencyKey:key}):await sendAttentionReminders({assignmentIds:ids,idempotencyKey:key});if(result.ok||!result.retryable)operation.current=null;setFeedback({result,targets:targetMap});if(result.ok){setSelected(new Set());router.refresh();}}catch{setFeedback({result:{ok:false,message:"通信結果を確認できませんでした。同じ操作を再度お試しください。",retryable:true},targets:targetMap});}});
  }
  const selectedItems=eligible.filter(item=>selected.has(item.assignmentId!));
  return <section aria-labelledby="attention-queue-title" className="min-w-0 overflow-hidden rounded-panel border border-border bg-surface">
    <div className="flex flex-col gap-3 border-b border-border px-4 py-3 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div><h2 id="attention-queue-title" className="font-semibold">優先度順</h2><p className="mt-0.5 text-xs text-foreground-muted">現在の業務状態から自動で更新されます</p></div><div className="flex flex-wrap items-center gap-2"><span className="mr-1 text-sm font-semibold tabular-nums">{items.length}件</span>{eligible.length>0&&<><span className="text-xs text-foreground-muted">通知候補 {selected.size}名</span><button type="button" disabled={pending||selected.size===0} onClick={()=>execute(selectedItems)} className="min-h-11 rounded-control bg-primary px-4 text-sm font-semibold text-primary-foreground hover:bg-primary-hover focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus-ring disabled:bg-surface-muted disabled:text-foreground-disabled">{pending&&selected.size>1?"再通知中…":`選択した対象へ再通知${selected.size?`（${selected.size}件）`:""}`}</button></>}</div></div>
    {feedback&&<ResultFeedback feedback={feedback}/>}
    <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[960px] border-collapse text-left text-sm"><thead className="bg-surface-subtle text-xs text-foreground-muted"><tr><th className="px-4 py-3 font-semibold">選択</th><th className="px-3 py-3 font-semibold">優先度</th><th className="px-3 py-3 font-semibold">種別</th><th className="px-3 py-3 font-semibold">問題</th><th className="px-3 py-3 font-semibold">対象</th><th className="px-3 py-3 font-semibold">発生</th><th className="px-4 py-3 font-semibold">Action</th></tr></thead><tbody className="divide-y divide-border">{items.map(item=><tr key={item.id}><td className="px-4 py-4 align-top">{item.type==="pre_confirmation_overdue"&&item.assignmentId?<input type="checkbox" checked={selected.has(item.assignmentId)} disabled={pending||(!selected.has(item.assignmentId)&&selected.size>=50)} onChange={()=>toggle(item.assignmentId!)} aria-label={`${item.target}を再通知対象に選択`} className="size-5"/>:<span aria-hidden className="inline-block size-5"/>}</td><td className="px-3 py-4 align-top"><Severity item={item}/></td><td className="px-3 py-4 align-top font-medium">{typeLabel[item.type]}</td><td className="max-w-md px-3 py-4 align-top"><p className="font-semibold text-foreground">{item.title}</p><p className="mt-1 text-xs text-foreground-muted">{item.description}</p></td><td className="px-3 py-4 align-top text-foreground-secondary">{item.target}</td><td className="whitespace-nowrap px-3 py-4 align-top text-xs text-foreground-muted">{dateTime.format(new Date(item.occurredAt))}</td><td className="px-4 py-4 align-top"><Actions item={item} pending={pending} onRemind={()=>item.type==="pre_confirmation_overdue"&&execute([item])}/></td></tr>)}</tbody></table></div>
    <ul className="divide-y divide-border md:hidden">{items.map(item=><li key={item.id} className="p-4"><div className="flex flex-wrap items-center gap-2">{item.type==="pre_confirmation_overdue"&&item.assignmentId&&<input type="checkbox" checked={selected.has(item.assignmentId)} disabled={pending||(!selected.has(item.assignmentId)&&selected.size>=50)} onChange={()=>toggle(item.assignmentId!)} aria-label={`${item.target}を再通知対象に選択`} className="size-5"/>}<Severity item={item}/><span className="text-xs font-semibold text-foreground-secondary">{typeLabel[item.type]}</span><time className="ml-auto text-xs text-foreground-muted">{dateTime.format(new Date(item.occurredAt))}</time></div><p className="mt-3 font-semibold">{item.title}</p><p className="mt-1 text-sm text-foreground-muted">{item.description}</p><p className="mt-2 text-sm text-foreground-secondary">{item.target}</p><div className="mt-4"><Actions item={item} pending={pending} onRemind={()=>item.type==="pre_confirmation_overdue"&&execute([item])}/></div></li>)}</ul>
  </section>;
}
function ResultFeedback({feedback}:{feedback:Feedback}){const{result,targets}=feedback;if(!result.ok)return <div role="alert" className="border-b border-border bg-danger-subtle px-4 py-3 text-sm text-danger-foreground sm:px-5">{result.message}</div>;const summary=result.status==="complete"?`${result.counts.projected}件のアプリ内通知を作成しました。`:result.status==="no_recipient"?"通知先が有効ではないため、通知は作成されませんでした。":result.status==="no_action"?"現在通知できる対象はありませんでした。":`${result.counts.projected}件の通知を作成し、${result.counts.skipped}件は作成されませんでした。`;return <div role="status" className="border-b border-border bg-info-subtle px-4 py-3 text-sm sm:px-5"><p className="font-semibold">{summary}</p><p className="mt-1 text-xs text-foreground-secondary">これはアプリ内通知の作成結果です。外部配信の完了を示すものではありません。</p><ul className="mt-2 flex flex-wrap gap-2">{result.items.map(item=><li key={item.assignmentId} className="rounded-pill bg-surface px-2.5 py-1 text-xs"><span className="font-medium">{targets.get(item.assignmentId)??"対象"}</span>: {outcomeLabel[item.outcome]}</li>)}</ul></div>;}
function Severity({item}:{item:AttentionItem}){return <span className={`inline-flex min-h-7 items-center rounded-ds-pill px-3 text-xs font-semibold ${severityClass[item.severity]}`}>{severityLabel[item.severity]}</span>;}
function Actions({item,pending,onRemind}:{item:AttentionItem;pending:boolean;onRemind:()=>void}){return <div className="flex flex-wrap gap-1"><Link href={item.destination} className="inline-flex min-h-11 items-center rounded-control px-2 text-sm font-semibold text-link hover:bg-surface-hover hover:underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus-ring">{item.actionLabel}<span aria-hidden="true">›</span></Link>{item.type==="pre_confirmation_overdue"&&<button type="button" disabled={pending} onClick={onRemind} className="min-h-11 rounded-control border border-border-strong px-3 text-sm font-semibold hover:bg-surface-hover focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus-ring disabled:text-foreground-disabled">{pending?"再通知中…":"再通知"}</button>}</div>;}
