"use client";
import { useMemo,useState } from "react";
import { AlertTriangle,Plus,Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { mutateJobRequirement } from "@/app/actions/job-requirements";
import type { ProjectDetailJob,StructuredRequirementItem } from "@/lib/admin/projects/project-detail-types";

export function JobStructuredRequirements({job}:{job:Pick<ProjectDetailJob,"id"|"structuredRequirements">}){const router=useRouter();const[pending,setPending]=useState<string>();const[message,setMessage]=useState<{kind:"success"|"error";text:string}>();const data=job.structuredRequirements;const skillAvailable=useMemo(()=>data.skillOptions.filter(option=>!data.skills.some(item=>item.id===option.id)),[data]);const qualificationAvailable=useMemo(()=>data.qualificationOptions.filter(option=>!data.qualifications.some(item=>item.id===option.id)),[data]);async function mutate(kind:"skill"|"qualification",operation:"add"|"remove",masterId:string){const key=`${kind}-${operation}-${masterId}`;setPending(key);setMessage(undefined);const result=await mutateJobRequirement({jobId:job.id,masterId,kind,operation});setPending(undefined);if(!result.ok){setMessage({kind:"error",text:result.message});return}setMessage({kind:"success",text:operation==="add"?"必須要件を追加しました。":"必須要件を削除しました。"});router.refresh()}
  return <section aria-labelledby={`structured-requirements-${job.id}`} className="mt-6 rounded-panel border border-border bg-surface p-4 sm:p-6"><div><h3 id={`structured-requirements-${job.id}`} className="text-base font-semibold">構造化された必須要件</h3><p className="mt-1 text-sm text-foreground-muted">Candidate判定に使用する必須Skill・資格です。上の「応募条件（自由記述）」とは別に保持されます。</p></div>{message&&<p role="status" className={`mt-4 rounded-control p-3 text-sm ${message.kind==="success"?"bg-success-subtle text-success":"bg-danger-subtle text-danger"}`}>{message.text}</p>}<div className="mt-5 grid gap-5 lg:grid-cols-2"><RequirementGroup label="必須Skill" kind="skill" items={data.skills} options={skillAvailable} pending={pending} mutate={mutate}/><RequirementGroup label="必須資格" kind="qualification" items={data.qualifications} options={qualificationAvailable} pending={pending} mutate={mutate}/></div></section>;
}
function RequirementGroup({label,kind,items,options,pending,mutate}:{label:string;kind:"skill"|"qualification";items:StructuredRequirementItem[];options:StructuredRequirementItem[];pending?:string;mutate:(kind:"skill"|"qualification",operation:"add"|"remove",masterId:string)=>Promise<void>}){const[selected,setSelected]=useState(options[0]?.id??"");const current=options.some(option=>option.id===selected)?selected:options[0]?.id??"";return <div className="min-w-0 rounded-control border border-border bg-surface-subtle p-4"><h4 className="font-semibold">{label}</h4>{items.length?<ul className="mt-3 space-y-2">{items.map(item=><li key={item.id} className="flex min-w-0 items-center justify-between gap-3 rounded-control bg-surface px-3 py-2"><div className="min-w-0"><p className="truncate text-sm font-medium">{item.name} <span className="font-mono text-xs text-foreground-muted">{item.code}</span></p>{!item.isActive&&<p className="mt-1 flex items-center gap-1 text-xs font-medium text-warning"><AlertTriangle className="size-3.5"/>Master無効 — 設定を確認してください</p>}</div><button type="button" aria-label={`${item.name}を必須要件から削除`} disabled={Boolean(pending)} onClick={()=>mutate(kind,"remove",item.id)} className="grid min-h-11 min-w-11 shrink-0 place-items-center rounded-control text-danger hover:bg-danger-subtle disabled:opacity-50"><Trash2 className="size-4"/></button></li>)}</ul>:<p className="mt-3 text-sm text-foreground-muted">設定されていません。</p>}<div className="mt-4 flex flex-col gap-2 sm:flex-row"><label className="sr-only" htmlFor={`${kind}-requirement-select`}>{label}を選択</label><select id={`${kind}-requirement-select`} value={current} disabled={options.length===0||Boolean(pending)} onChange={event=>setSelected(event.target.value)} className="min-h-11 min-w-0 flex-1 rounded-control border border-border-strong bg-surface px-3 text-sm disabled:bg-surface-muted"><option value="">{options.length?"選択してください":"追加できる有効なマスタはありません"}</option>{options.map(option=><option key={option.id} value={option.id}>{option.name} ({option.code})</option>)}</select><button type="button" disabled={!current||Boolean(pending)} onClick={()=>mutate(kind,"add",current)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-control border border-border-strong bg-surface px-4 text-sm font-medium text-link hover:bg-surface-hover disabled:text-foreground-disabled"><Plus className="size-4"/>追加</button></div></div>}
