import Link from "next/link";
import { AlertTriangle,Building2,Users } from "lucide-react";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import type { AdminAnnouncement,AnnouncementActor } from "@/lib/admin/announcements/announcement-types";
import { AnnouncementActions } from "./announcement-actions";
import { AnnouncementStatusBadge } from "./announcement-status-badge";

const formatter=new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false});
function date(value:string|null){return value?formatter.format(new Date(value)):"—";}
export function AnnouncementDetail({announcement,actor}:{announcement:AdminAnnouncement;actor:AnnouncementActor}){const audience=announcement.scopeType==="organization"?"全Worker":`${announcement.branchName??"拠点"}の有効Worker`;return <><AdminPageHeader eyebrow={<AnnouncementStatusBadge state={announcement.state}/>} title={announcement.title||"無題のお知らせ"} description={announcement.state==="draft"?"下書きは公開前に編集できます。":announcement.state==="published"?"公開済みのお知らせは読み取り専用です。":"アーカイブ済みのお知らせは読み取り専用です。"} actions={announcement.state==="draft"?<Link href={`/admin/announcements/${announcement.id}?edit=1`} className="inline-flex min-h-11 items-center rounded-control bg-primary px-5 text-sm font-semibold text-primary-foreground hover:bg-primary-hover">下書きを編集</Link>:undefined}/><div className="grid min-w-0 gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(18rem,.65fr)]"><section aria-labelledby="announcement-content-title" className="rounded-panel border border-border bg-surface p-4 sm:p-6"><div className="flex flex-wrap items-center gap-2"><h2 id="announcement-content-title" className="text-lg font-semibold">お知らせ内容</h2>{announcement.importance==="important"&&<span className="inline-flex items-center gap-1 rounded-ds-pill bg-warning-subtle px-2.5 py-1 text-xs font-semibold text-warning-foreground"><AlertTriangle aria-hidden className="size-3.5"/>重要</span>}</div><p className="mt-5 whitespace-pre-wrap break-words text-sm leading-7 text-foreground-secondary">{announcement.body||"本文はまだ入力されていません。"}</p></section><aside className="space-y-4"><section aria-labelledby="announcement-target-title" className="rounded-panel border border-border bg-surface p-4 sm:p-5"><h2 id="announcement-target-title" className="text-base font-semibold">公開対象</h2><p className="mt-3 flex items-center gap-2 text-sm font-medium">{announcement.scopeType==="organization"?<Users aria-hidden className="size-4"/>:<Building2 aria-hidden className="size-4"/>}{audience}</p>{announcement.state!=="draft"&&<p className="mt-2 text-sm text-foreground-muted">公開時に確定: {announcement.recipientCount}名</p>}</section><section aria-labelledby="announcement-history-title" className="rounded-panel border border-border bg-surface p-4 sm:p-5"><h2 id="announcement-history-title" className="text-base font-semibold">履歴</h2><dl className="mt-3 grid grid-cols-[auto_1fr] gap-x-3 gap-y-2 text-sm"><dt className="text-foreground-muted">作成</dt><dd>{date(announcement.createdAt)}</dd><dt className="text-foreground-muted">公開</dt><dd>{date(announcement.publishedAt)}</dd><dt className="text-foreground-muted">アーカイブ</dt><dd>{date(announcement.archivedAt)}</dd></dl></section><AnnouncementActions announcement={announcement}/></aside></div>{announcement.state==="draft"&&actor.branches.length===0&&<p role="alert" className="text-sm text-danger">利用可能な拠点がないため、拠点対象へ変更できません。</p>}</>}
