import Link from "next/link";
import { AlertTriangle, Building2, Users } from "lucide-react";
import type { AdminAnnouncement } from "@/lib/admin/announcements/announcement-types";
import { AnnouncementStatusBadge } from "./announcement-status-badge";

const formatter=new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false});
function date(value:string|null){return value?formatter.format(new Date(value)):"—";}
export function AnnouncementList({items}:{items:AdminAnnouncement[]}){return <ul className="divide-y divide-border overflow-hidden rounded-panel border border-border bg-surface">{items.map(item=><li key={item.id} className="grid min-w-0 gap-3 p-4 sm:p-5 lg:grid-cols-[minmax(14rem,1.6fr)_minmax(10rem,.8fr)_minmax(11rem,.8fr)] lg:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><AnnouncementStatusBadge state={item.state}/>{item.importance==="important"&&<span className="inline-flex items-center gap-1 rounded-ds-pill bg-warning-subtle px-2.5 py-1 text-xs font-semibold text-warning-foreground"><AlertTriangle aria-hidden className="size-3.5"/>重要</span>}</div><h2 className="mt-2 min-w-0 text-base font-semibold"><Link href={`/admin/announcements/${item.id}`} className="break-words text-link underline-offset-4 hover:underline focus-visible:rounded-sm focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus-ring">{item.title||"無題のお知らせ"}</Link></h2><p className="mt-1 text-xs text-foreground-muted">作成 {date(item.createdAt)}</p></div><div className="text-sm"><p className="flex items-center gap-2 font-medium">{item.scopeType==="organization"?<Users aria-hidden className="size-4"/>:<Building2 aria-hidden className="size-4"/>}{item.scopeType==="organization"?"全Worker":item.branchName??"拠点"}</p>{item.state!=="draft"&&<p className="mt-1 text-xs text-foreground-muted">対象 {item.recipientCount}名</p>}</div><dl className="grid grid-cols-[auto_1fr] gap-x-3 gap-y-1 text-xs"><dt className="text-foreground-muted">公開</dt><dd>{date(item.publishedAt)}</dd><dt className="text-foreground-muted">アーカイブ</dt><dd>{date(item.archivedAt)}</dd></dl></li>)}</ul>;}

