import { MapPin } from "lucide-react";
import Link from "next/link";
import type { ProjectDetailJob } from "@/lib/admin/projects/project-detail-types";
import { JOB_STATUS_LABELS } from "@/lib/admin/projects/project-detail-rules";
import { ProjectShiftList } from "./project-shift-list";

export function ProjectJobItem({ projectId, job }: { projectId: string; job: ProjectDetailJob }) {
  return <li className={`rounded-lg border bg-white p-4 sm:p-5 ${job.shortage > 0 ? "border-amber-300" : "border-slate-200"}`}><div className="grid gap-4 lg:grid-cols-[minmax(0,1.2fr)_minmax(16rem,.8fr)_auto] lg:items-center"><div><h3 className="text-base font-semibold text-slate-950">{job.name}</h3><p className="mt-1 text-sm font-medium text-slate-700">{job.workplace.name}</p><p className="mt-2 flex items-start gap-2 text-sm text-slate-500"><MapPin aria-hidden="true" className="mt-0.5 size-4 shrink-0" />{job.workplace.address}</p></div><dl className="grid grid-cols-2 gap-3 text-sm"><div><dt className="text-slate-500">シフト</dt><dd className="font-semibold text-slate-950">{job.shiftCount}件</dd></div><div><dt className="text-slate-500">配置</dt><dd className="font-semibold text-slate-950">{job.assignedWorkers} / {job.requiredWorkers}名</dd></div><div><dt className="text-slate-500">不足</dt><dd className={job.shortage > 0 ? "font-semibold text-red-700" : "font-semibold text-slate-950"}>{job.shortage}名</dd></div></dl><div className="flex flex-wrap gap-2 lg:justify-end"><span className="rounded bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700">{JOB_STATUS_LABELS[job.status]}</span><span className={`rounded px-2.5 py-1 text-xs font-semibold ${job.shortage > 0 ? "bg-amber-50 text-amber-800" : "bg-emerald-50 text-emerald-800"}`}>{job.shortage > 0 ? "要確認" : "配置完了"}</span><Link href={`/admin/projects/${projectId}/jobs/${job.id}/shifts/new`} className="inline-flex min-h-10 items-center rounded-md border border-slate-300 px-3 text-xs font-semibold text-slate-700 hover:bg-slate-50">シフトを追加</Link><Link href={`/admin/projects/${projectId}/jobs/${job.id}/shifts/bulk-new`} className="inline-flex min-h-10 items-center rounded-md border border-blue-300 px-3 text-xs font-semibold text-blue-700 hover:bg-blue-50">複数日まとめて追加</Link></div></div><ProjectShiftList shifts={job.shifts} /></li>;
}
