import type { ProjectDetailShift } from "@/lib/admin/projects/project-detail-types";
import { SHIFT_STATUS_LABELS } from "@/lib/admin/projects/project-detail-rules";
import Link from "next/link";

const day = new Intl.DateTimeFormat("ja-JP", { timeZone: "Asia/Tokyo", month: "numeric", day: "numeric", weekday: "short" });
const time = new Intl.DateTimeFormat("ja-JP", { timeZone: "Asia/Tokyo", hour: "2-digit", minute: "2-digit", hour12: false });
export function ProjectShiftList({ shifts }: { shifts: ProjectDetailShift[] }) {
  if (!shifts.length) return <div className="border-t border-slate-200 bg-slate-50 px-4 py-5 sm:px-5"><p className="font-medium text-slate-800">シフトはまだ登録されていません。</p><p className="mt-1 text-sm text-slate-600">この業務の勤務日を、上の「シフトを追加」または「複数日まとめて追加」から登録してください。</p></div>;
  return <div className="border-t border-slate-200"><div className="bg-slate-50 px-4 py-2 sm:px-5"><h4 className="text-sm font-semibold text-slate-800">シフト</h4></div><ul aria-label="シフト一覧" className="divide-y divide-slate-200">{shifts.map((shift) => <li key={shift.id} className="grid gap-3 px-4 py-3 sm:grid-cols-[minmax(8rem,.8fr)_minmax(8rem,.7fr)_minmax(13rem,1.2fr)_auto] sm:items-center sm:px-5"><div><p className="text-sm font-semibold"><Link href={`/admin/shifts/${shift.id}`} className="inline-flex min-h-10 items-center text-blue-800 underline-offset-4 hover:underline focus-visible:rounded-sm focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600">{day.format(new Date(shift.startsAt))}</Link></p>{shift.label && <p className="text-xs text-slate-500">{shift.label}</p>}</div><p className="text-sm font-medium text-slate-800">{time.format(new Date(shift.startsAt))}〜{time.format(new Date(shift.endsAt))}</p><dl className="grid grid-cols-3 gap-3 text-sm"><div><dt className="text-xs text-slate-500">必要</dt><dd className="font-semibold text-slate-950">{shift.requiredWorkers}名</dd></div><div><dt className="text-xs text-slate-500">配置</dt><dd className="font-semibold text-slate-950">{shift.assignedWorkers}名</dd></div><div><dt className="text-xs text-slate-500">不足</dt><dd className={shift.shortage > 0 ? "font-semibold text-red-700" : "font-semibold text-slate-950"}>{shift.shortage}名</dd></div></dl><div className="flex flex-wrap items-center gap-2 sm:justify-end"><span className="rounded bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700">{SHIFT_STATUS_LABELS[shift.status]}</span><span className={`rounded px-2.5 py-1 text-xs font-semibold ${shift.shortage > 0 ? "bg-red-50 text-red-800" : "bg-emerald-50 text-emerald-800"}`}>{shift.shortage > 0 ? `${shift.shortage}名不足` : "配置完了"}</span></div></li>)}</ul></div>;
}
