import Link from "next/link";
import { AdminEmptyState, AdminErrorState, AdminNotFoundState, adminStateActionClass } from "@/components/admin/admin-state";
import { AdminPage } from "@/components/admin/admin-page";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { IncidentDrawer } from "@/components/admin/incidents/incident-drawer";
import { IncidentList } from "@/components/admin/incidents/incident-list";
import { adminIncidentHref, parseAdminIncidentQuery } from "@/lib/admin/incidents/incident-rules";
import { getAdminIncidents } from "@/lib/admin/incidents/get-admin-incidents";
import { OPERATIONAL_INCIDENT_CATEGORIES, incidentCategoryLabels } from "@/lib/worker/incidents/worker-incident-ui";

const control="mt-1.5 min-h-11 w-full rounded-control border border-border-strong bg-surface px-3 text-sm focus-visible:outline-2 focus-visible:outline-focus-ring";
export default async function IncidentsPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const query=parseAdminIncidentQuery(await searchParams);const result=await getAdminIncidents(query);const filtered=Boolean(query.q||query.category||query.state!=="unresolved");return <AdminPage><AdminPageHeader title="ヘルプリクエスト" description="スタッフから届いた勤務上のHelp Requestを確認し、対応開始から解決まで管理します。"/>
  {result.ok&&<section aria-label="集計" className="grid overflow-hidden rounded-panel border border-border bg-surface sm:grid-cols-3">{[["未対応",result.summary.open,"件"],["対応中",result.summary.acknowledged,"件"],["本日解決",result.summary.resolvedToday,"件"]].map(([label,value,unit])=><div key={label} className="border-border px-4 py-3 sm:border-r sm:last:border-r-0"><p className="text-xs text-foreground-muted">{label}</p><p className="mt-0.5 text-xl font-semibold tabular-nums">{value}<span className="ml-1 text-xs font-normal text-foreground-muted">{unit}</span></p></div>)}</section>}
  <form method="get" className="rounded-panel border border-border bg-surface p-4"><div className="grid gap-3 md:grid-cols-[minmax(14rem,1.5fr)_minmax(10rem,1fr)_minmax(10rem,1fr)_auto] md:items-end"><label className="text-sm font-medium">検索<input name="q" type="search" defaultValue={query.q} placeholder="スタッフ・案件・業務・勤務先" maxLength={100} className={control}/></label><label className="text-sm font-medium">状態<select name="state" defaultValue={query.state} className={control}><option value="unresolved">未解決</option><option value="open">未対応</option><option value="acknowledged">対応中</option><option value="resolved">解決済み</option><option value="retracted">取り下げ</option><option value="all">すべて</option></select></label><label className="text-sm font-medium">カテゴリ<select name="category" defaultValue={query.category} className={control}><option value="">すべて</option>{OPERATIONAL_INCIDENT_CATEGORIES.map(value=><option key={value} value={value}>{incidentCategoryLabels[value]}</option>)}</select></label><button className="min-h-11 rounded-control bg-primary px-5 text-sm font-semibold text-primary-foreground">検索</button></div>{filtered&&<div className="mt-3 flex justify-end"><Link href="/admin/incidents" className={adminStateActionClass}>条件をリセット</Link></div>}</form>
  {!result.ok ? <AdminErrorState title="ヘルプリクエストを取得できませんでした。"/> : result.items.length===0 ? <AdminEmptyState title="条件に一致するヘルプリクエストはありません。" description={filtered?"検索条件を変更してください。":"現在、未解決のHelp Requestはありません。"}/> : <><p className="text-sm text-foreground-muted">{result.total}件</p><IncidentList items={result.items} query={query}/>{result.totalPages>1&&<nav aria-label="ページ" className="flex items-center justify-center gap-3"><Link aria-disabled={result.page===1} href={adminIncidentHref(query,{page:Math.max(1,result.page-1),incident:""})} className={adminStateActionClass}>前へ</Link><span className="text-sm">{result.page} / {result.totalPages}</span><Link aria-disabled={result.page===result.totalPages} href={adminIncidentHref(query,{page:Math.min(result.totalPages,result.page+1),incident:""})} className={adminStateActionClass}>次へ</Link></nav>}</>}
  {query.incident&&(result.ok&&result.selected?<IncidentDrawer incident={result.selected} events={result.events} closeHref={adminIncidentHref(query,{incident:""})}/>:<div className="fixed inset-0 z-50 grid place-items-center bg-[var(--surface-overlay)] p-4"><AdminNotFoundState><Link href={adminIncidentHref(query,{incident:""})} className={adminStateActionClass}>一覧へ戻る</Link></AdminNotFoundState></div>)}
  </AdminPage>}
