"use client";

import Link from "next/link";
import { useMemo, useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { ChevronDown, ChevronUp, Plus, X } from "lucide-react";
import { Drawer } from "@/components/admin/drawer";
import { AdminFeedback, adminStateActionClass } from "@/components/admin/admin-state";
import { savePlacementPlan } from "@/app/actions/placement";
import { plannedMinutes, positionCoverage, resolveShiftTime, timelineGeometry, timelineMarkers, toTimeValue, validatePlacementDraft } from "@/lib/admin/placement/placement-editor-rules";
import type { PlacementBreak, PlacementPlan, PlacementSegment } from "@/lib/admin/placement/placement-types";

const field = "min-h-11 w-full rounded-control border border-border-strong bg-surface px-3 text-sm focus-visible:outline-2 focus-visible:outline-focus-ring";
const primary = "min-h-11 rounded-control bg-primary px-5 text-sm font-semibold text-primary-foreground disabled:bg-surface-muted focus-visible:outline-2 focus-visible:outline-focus-ring";
const newId = () => crypto.randomUUID();

export function PlacementEditor({ initial, closeHref, shiftLabel }: { initial: PlacementPlan; closeHref: string; shiftLabel: string }) {
  const router = useRouter(); const [draft, setDraft] = useState(initial); const [baseline, setBaseline] = useState(JSON.stringify(initial));
  const [result, setResult] = useState<{ kind: "success" | "error" | "conflict"; message: string } | null>(null); const [pending, startTransition] = useTransition();
  const [picker, setPicker] = useState(false); const [search, setSearch] = useState(""); const idempotency = useRef(newId());
  const dirty = JSON.stringify(draft) !== baseline; const errors = useMemo(() => validatePlacementDraft(draft), [draft]);
  const activePositions = draft.positions.filter((p) => !p.retired).sort((a, b) => a.displayOrder - b.displayOrder);
  const close = () => { if (!dirty || window.confirm("未保存の変更を破棄して閉じますか？")) router.push(closeHref, { scroll: false }); };
  const updateTime = (kind: "segments" | "breaks", id: string, key: "startAt" | "endAt", value: string) => setDraft((old) => ({ ...old, [kind]: old[kind].map((row) => row.id === id ? { ...row, [key]: resolveShiftTime(value, old) ?? row[key] } : row) }));
  const save = () => startTransition(async () => {
    setResult(null); const checked = validatePlacementDraft(draft); if (checked.length) { setResult({ kind: "error", message: checked[0] }); return; }
    const saved = await savePlacementPlan({ shiftId: draft.shiftId, version: draft.version, positions: draft.positions, segments: draft.segments, breaks: draft.breaks, reason: (document.getElementById("placement-reason") as HTMLTextAreaElement | null)?.value ?? "", idempotencyKey: idempotency.current });
    if (!saved.ok) { setResult({ kind: saved.type === "conflict" ? "conflict" : "error", message: saved.message }); return; }
    const next = { ...draft, version: saved.version }; setDraft(next); setBaseline(JSON.stringify(next)); idempotency.current = newId(); setResult({ kind: "success", message: "配置・休憩を保存しました。" }); router.refresh();
  });
  const addSegment = (assignmentId: string) => { if (!activePositions[0]) return; setDraft((old) => ({ ...old, segments: [...old.segments, { id: newId(), assignmentId, positionId: activePositions[0].id, startAt: old.startsAt, endAt: old.endsAt }] })); setPicker(false); };
  const candidates = draft.assignments.filter((a) => [a.worker?.name, a.worker?.staffCode].some((v) => v?.toLocaleLowerCase("ja").includes(search.toLocaleLowerCase("ja"))));
  return <Drawer open titleId="placement-editor-title" closeDisabled={pending} onClose={close} width="wide">
    <header className="sticky top-0 z-20 flex items-start justify-between border-b border-border bg-surface p-4 sm:p-6"><div><p className="text-sm font-medium text-link">配置・休憩回し</p><h2 id="placement-editor-title" className="mt-1 text-xl font-semibold">{shiftLabel}</h2><p className="mt-1 text-xs text-foreground-muted">{toTimeValue(draft.startsAt)}–{toTimeValue(draft.endsAt)}・{draft.requiredWorkers}名</p></div><button autoFocus type="button" onClick={close} disabled={pending} aria-label="配置エディタを閉じる" className="inline-flex size-11 items-center justify-center rounded-control hover:bg-surface-hover"><X aria-hidden className="size-5" /></button></header>
    <div className="space-y-6 p-4 pb-28 sm:p-6 sm:pb-28">
      {result && <AdminFeedback kind={result.kind} message={result.message}>{result.kind === "conflict" && <button type="button" onClick={() => window.location.reload()} className={adminStateActionClass}>最新の配置を読み込む</button>}</AdminFeedback>}
      {dirty && !pending && <AdminFeedback kind="unsaved" message="未保存の変更があります。" />}{pending && <AdminFeedback kind="pending" message="配置プラン全体を保存しています。" />}
      <section aria-labelledby="positions-heading"><div className="flex items-center justify-between gap-3"><div><h3 id="positions-heading" className="font-semibold">配置ポジション</h3><p className="text-xs text-foreground-muted">必要人数合計 {activePositions.reduce((n,p)=>n+(p.requiredWorkers??0),0)} / {draft.requiredWorkers}</p></div><button type="button" onClick={() => setDraft((old) => ({ ...old, positions: [...old.positions, { id: newId(), label: "", requiredWorkers: null, displayOrder: activePositions.length, retired: false }] }))} className={adminStateActionClass}><Plus aria-hidden className="mr-1 size-4" />追加</button></div>
        <ul className="mt-3 space-y-3">{activePositions.map((position, index) => <li key={position.id} className="rounded-card border border-border p-3"><div className="grid gap-3 sm:grid-cols-[1fr_8rem_auto]"><label className="text-xs font-medium">名称<input aria-label="ポジション名" value={position.label} maxLength={200} onChange={(e)=>setDraft((old)=>({...old,positions:old.positions.map((p)=>p.id===position.id?{...p,label:e.target.value}:p)}))} className={`${field} mt-1`} /></label><label className="text-xs font-medium">必要人数<input aria-label="必要人数" type="number" min="0" value={position.requiredWorkers ?? ""} onChange={(e)=>setDraft((old)=>({...old,positions:old.positions.map((p)=>p.id===position.id?{...p,requiredWorkers:e.target.value===""?null:Number(e.target.value)}:p)}))} className={`${field} mt-1`} /></label><div className="flex items-end gap-1"><button type="button" aria-label="上へ" disabled={index===0} onClick={()=>setDraft((old)=>{const ordered=old.positions.filter(p=>!p.retired).sort((a,b)=>a.displayOrder-b.displayOrder);[ordered[index-1],ordered[index]]=[ordered[index],ordered[index-1]];return {...old,positions:old.positions.map(p=>{const i=ordered.findIndex(x=>x.id===p.id);return i>=0?{...p,displayOrder:i}:p;})}})} className="size-11 rounded-control border border-border disabled:opacity-40"><ChevronUp className="mx-auto size-4" /></button><button type="button" aria-label="下へ" disabled={index===activePositions.length-1} onClick={()=>setDraft((old)=>{const ordered=old.positions.filter(p=>!p.retired).sort((a,b)=>a.displayOrder-b.displayOrder);[ordered[index],ordered[index+1]]=[ordered[index+1],ordered[index]];return {...old,positions:old.positions.map(p=>{const i=ordered.findIndex(x=>x.id===p.id);return i>=0?{...p,displayOrder:i}:p;})}})} className="size-11 rounded-control border border-border disabled:opacity-40"><ChevronDown className="mx-auto size-4" /></button></div></div><button type="button" onClick={()=>setDraft((old)=>({...old,positions:old.positions.map(p=>p.id===position.id?{...p,retired:true}:p)}))} className="mt-2 min-h-11 text-sm font-medium text-danger">この配置枠を終了</button></li>)}</ul>
      </section>
      <PlacementTimeline plan={draft} />
      <section aria-labelledby="staff-heading"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 id="staff-heading" className="font-semibold">スタッフ配置</h3><p className="text-xs text-foreground-muted">このシフトにAssignment済みのスタッフから選択します</p></div><button type="button" disabled={!activePositions.length} onClick={()=>setPicker(true)} className={adminStateActionClass}><Plus aria-hidden className="mr-1 size-4" />配置スタッフを選択</button></div>
        {picker && <div role="dialog" aria-modal="true" aria-labelledby="picker-title" className="mt-3 rounded-card border-2 border-primary bg-surface p-3"><div className="flex justify-between"><div><h4 id="picker-title" className="font-semibold">配置スタッフを選択</h4><p className="mt-1 text-xs text-foreground-muted">新しいAssignmentは作成しません。</p></div><button type="button" onClick={()=>setPicker(false)} aria-label="スタッフ選択を閉じる" className="size-11 rounded-control hover:bg-surface-hover"><X className="mx-auto size-4" /></button></div><label className="mt-3 block text-xs font-medium">スタッフを検索<input autoFocus type="search" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="氏名・スタッフIDで検索" className={`${field} mt-1`} /></label><ul className="mt-2 max-h-60 overflow-y-auto divide-y divide-border">{candidates.map((a)=><li key={a.assignmentId} className="flex min-h-14 items-center justify-between gap-3 py-2"><div className="min-w-0"><p className="truncate text-sm font-medium">{a.worker?.name ?? "スタッフ情報を表示できません"}</p><p className="truncate text-xs text-foreground-muted">{a.worker?.staffCode}・{a.status}{draft.segments.some(s=>s.assignmentId===a.assignmentId)&&"・配置あり"}</p></div><button type="button" onClick={()=>addSegment(a.assignmentId)} className={`${adminStateActionClass} shrink-0`}>時間帯を追加</button></li>)}</ul>{candidates.length === 0 && <p className="py-4 text-center text-sm text-foreground-muted">一致するスタッフはいません。</p>}</div>}
        <ul className="mt-3 space-y-4">{draft.assignments.map((a)=><li key={a.assignmentId} className="rounded-panel border border-border p-4"><div className="flex flex-wrap justify-between gap-2"><div>{a.worker?<Link href={`/admin/workers/${a.worker.id}`} className="inline-flex min-h-11 items-center font-semibold text-link hover:underline">{a.worker.name}</Link>:<p className="font-semibold">スタッフ情報を表示できません</p>}<p className="text-xs text-foreground-muted">{a.worker?.staffCode}・{a.status}</p></div><p className="text-xs text-foreground-muted">配置 {plannedMinutes(draft.segments.filter(s=>s.assignmentId===a.assignmentId))}分 / 休憩 {plannedMinutes(draft.breaks.filter(b=>b.assignmentId===a.assignmentId))}分</p></div>
          <IntervalList kind="segments" rows={draft.segments.filter(s=>s.assignmentId===a.assignmentId)} positions={activePositions} onTime={updateTime} onPosition={(id,value)=>setDraft(old=>({...old,segments:old.segments.map(s=>s.id===id?{...s,positionId:value}:s)}))} onRemove={(id)=>setDraft(old=>({...old,segments:old.segments.filter(s=>s.id!==id)}))} />
          <div className="mt-3 flex items-center justify-between"><h5 className="text-sm font-semibold">休憩</h5><button type="button" onClick={()=>setDraft(old=>({...old,breaks:[...old.breaks,{id:newId(),assignmentId:a.assignmentId,startAt:old.startsAt,endAt:old.endsAt}]}))} className="min-h-11 text-sm font-medium text-link">＋ 休憩を追加</button></div><IntervalList kind="breaks" rows={draft.breaks.filter(b=>b.assignmentId===a.assignmentId)} positions={activePositions} onTime={updateTime} onRemove={(id)=>setDraft(old=>({...old,breaks:old.breaks.filter(b=>b.id!==id)}))} />
          {draft.breakMinutes != null && <BreakTarget planned={plannedMinutes(draft.breaks.filter(b=>b.assignmentId===a.assignmentId))} target={draft.breakMinutes} />}
          {errors.filter((message)=>message.includes(a.worker?.name ?? "スタッフ")).map((message)=><p role="alert" key={message} className="mt-2 rounded-control bg-danger-subtle p-3 text-xs font-medium text-danger-foreground">{message} 対象の時間を修正してください。</p>)}
        </li>)}</ul>
      </section>
      <section aria-labelledby="coverage-heading"><h3 id="coverage-heading" className="font-semibold">Coverage（派生値）</h3><ul className="mt-2 space-y-2">{activePositions.map((p)=>{const coverage=positionCoverage(p,draft.segments,draft.breaks);const shortage=coverage.filter(c=>c.shortage&&c.shortage>0);return <li key={p.id} className="rounded-card bg-surface-subtle p-3 text-sm"><span className="font-medium">{p.label||"名称未入力"}</span>：{p.requiredWorkers==null?"必要人数未設定":shortage.length?`不足時間帯 ${shortage.length}件`:`必要${p.requiredWorkers}名を充足`}</li>})}</ul></section>
      {errors.length>0 && <AdminFeedback kind="error" message={errors[0]} />}
      {draft.correctionRequired && <label className="block text-sm font-medium">開始後の変更理由<textarea id="placement-reason" required maxLength={500} rows={3} className={`${field} mt-1 py-2`} /><span className="mt-1 block text-xs text-foreground-muted">監査Revisionへ保存されます。</span></label>}
    </div>
    <footer className="fixed inset-x-0 bottom-0 ml-auto flex w-full max-w-4xl justify-end gap-3 border-t border-border bg-surface p-4 sm:p-5"><button type="button" onClick={close} disabled={pending} className={adminStateActionClass}>キャンセル</button><button type="button" onClick={save} disabled={pending||errors.length>0} className={primary}>{pending?"保存中…":"配置プランを保存"}</button></footer>
  </Drawer>;
}

function BreakTarget({ planned, target }: { planned: number; target: number }) {
  const delta = planned - target; const exact = delta === 0;
  return <p className={`mt-2 rounded-control px-3 py-2 text-xs ${exact ? "bg-success-subtle text-success-foreground" : "bg-warning-subtle text-warning-foreground"}`}>
    予定休憩 <span className="font-semibold tabular-nums">{planned} / {target}分</span>{!exact && <span className="ml-2">（{delta < 0 ? `不足${-delta}分` : `超過${delta}分`}・保存可能）</span>}
  </p>;
}

function PlacementTimeline({ plan }: { plan: PlacementPlan }) {
  const markers = timelineMarkers(plan.startsAt, plan.endsAt); const active = plan.positions.filter((p)=>!p.retired);
  return <section aria-labelledby="timeline-heading" className="border-y border-border py-5"><div className="flex flex-wrap items-end justify-between gap-2"><div><h3 id="timeline-heading" className="font-semibold">配置・休憩タイムライン</h3><p className="mt-1 text-xs text-foreground-muted">誰が何時にどのポジションへいるかを表示。休憩中はCoverageから除外します。</p></div><p className="text-xs tabular-nums text-foreground-muted">{toTimeValue(plan.startsAt)}–{toTimeValue(plan.endsAt)}</p></div>
    <div className="mt-4 hidden overflow-hidden rounded-panel border border-border sm:block" role="img" aria-label="スタッフ別の配置と休憩タイムライン">
      <div className="grid grid-cols-[9rem_1fr] bg-surface-subtle"><div className="border-r border-border p-2 text-xs font-medium">スタッフ</div><div className="relative h-10">{markers.map((m)=><div key={m.instant} className="absolute inset-y-0 border-l border-border-subtle" style={{left:`${m.percent}%`}}><span className={`absolute top-2 whitespace-nowrap text-[10px] text-foreground-muted ${m.percent===100?"right-1":"left-1"}`}>{m.label}</span></div>)}</div></div>
      {plan.assignments.map((assignment)=><div key={assignment.assignmentId} className="grid min-h-16 grid-cols-[9rem_1fr] border-t border-border"><div className="min-w-0 border-r border-border p-2"><p className="truncate text-xs font-medium">{assignment.worker?.name ?? "スタッフ情報なし"}</p><p className="truncate text-[10px] text-foreground-muted">{assignment.worker?.staffCode}</p></div><div className="relative m-2 min-h-11 rounded-control bg-surface-subtle">
        {plan.segments.filter(s=>s.assignmentId===assignment.assignmentId).map((segment)=>{const start=timelineGeometry(segment.startAt,plan.startsAt,plan.endsAt);const end=timelineGeometry(segment.endAt,plan.startsAt,plan.endsAt);const label=active.find(p=>p.id===segment.positionId)?.label??"配置枠終了";return <div key={segment.id} title={`${label} ${toTimeValue(segment.startAt)}–${toTimeValue(segment.endAt)}`} className="absolute inset-y-1 min-w-1 overflow-hidden rounded-control border border-primary bg-surface-selected px-2 text-[10px] font-medium leading-9 text-link" style={{left:`${start}%`,width:`${Math.max(0,end-start)}%`}}><span className="block truncate">{label}</span><span className="sr-only">{toTimeValue(segment.startAt)}から{toTimeValue(segment.endAt)}</span></div>})}
        {plan.breaks.filter(b=>b.assignmentId===assignment.assignmentId).map((row)=>{const start=timelineGeometry(row.startAt,plan.startsAt,plan.endsAt);const end=timelineGeometry(row.endAt,plan.startsAt,plan.endsAt);return <div key={row.id} title={`休憩 ${toTimeValue(row.startAt)}–${toTimeValue(row.endAt)}`} className="absolute inset-y-1 min-w-1 overflow-hidden rounded-control border border-dashed border-success-foreground bg-success-subtle px-2 text-[10px] font-semibold leading-9 text-success-foreground" style={{left:`${start}%`,width:`${Math.max(0,end-start)}%`}}><span className="block truncate">休憩</span><span className="sr-only">{toTimeValue(row.startAt)}から{toTimeValue(row.endAt)}</span></div>})}
      </div></div>)}
    </div>
    <ul className="mt-3 space-y-2 sm:hidden" aria-label="配置と休憩の時間一覧">{plan.assignments.map((assignment)=><li key={assignment.assignmentId} className="rounded-card bg-surface-subtle p-3"><p className="text-sm font-semibold">{assignment.worker?.name ?? "スタッフ情報なし"}</p><ul className="mt-2 space-y-1 text-xs">{plan.segments.filter(s=>s.assignmentId===assignment.assignmentId).map(s=><li key={s.id}><span className="font-medium">{active.find(p=>p.id===s.positionId)?.label??"配置枠終了"}</span> {toTimeValue(s.startAt)}–{toTimeValue(s.endAt)}</li>)}{plan.breaks.filter(b=>b.assignmentId===assignment.assignmentId).map(b=><li key={b.id} className="text-success-foreground"><span className="font-semibold">休憩</span> {toTimeValue(b.startAt)}–{toTimeValue(b.endAt)}</li>)}</ul></li>)}</ul>
  </section>;
}

function IntervalList({ kind, rows, positions, onTime, onPosition, onRemove }: { kind: "segments" | "breaks"; rows: (PlacementSegment|PlacementBreak)[]; positions: PlacementPlan["positions"]; onTime: (kind:"segments"|"breaks",id:string,key:"startAt"|"endAt",value:string)=>void; onPosition?: (id:string,value:string)=>void; onRemove:(id:string)=>void }) {
  if (!rows.length) return <p className="mt-2 text-xs text-foreground-muted">{kind==="segments"?"配置時間帯はありません。":"休憩はありません。"}</p>;
  return <ul className="mt-2 space-y-2">{rows.map((row)=><li key={row.id} className="grid gap-2 rounded-card bg-surface-subtle p-2 sm:grid-cols-[1fr_7rem_7rem_auto]">{kind==="segments"&&<select aria-label="ポジション" value={(row as PlacementSegment).positionId} onChange={(e)=>onPosition?.(row.id,e.target.value)} className={field}>{positions.map(p=><option key={p.id} value={p.id}>{p.label||"名称未入力"}</option>)}</select>}<input aria-label="開始時刻" type="time" step="900" value={toTimeValue(row.startAt)} onChange={(e)=>onTime(kind,row.id,"startAt",e.target.value)} className={field}/><input aria-label="終了時刻" type="time" step="900" value={toTimeValue(row.endAt)} onChange={(e)=>onTime(kind,row.id,"endAt",e.target.value)} className={field}/><button type="button" onClick={()=>onRemove(row.id)} className="min-h-11 px-2 text-sm font-medium text-danger">削除</button></li>)}</ul>;
}
