import Link from "next/link";
import { PreShiftStatusBadge } from "@/components/worker/pre-shift-status-badge";
import type { RecruitmentShift } from "@/lib/worker/recruitment/get-worker-recruitment";
import type { WorkerAssignment } from "@/lib/worker/worker-assignment-types";
import { selectWorkerHomeEndWork, selectWorkerHomeNextAction, selectWorkerHomeNextShift } from "@/lib/worker/home/worker-home";

const day = new Intl.DateTimeFormat("ja-JP", { timeZone: "Asia/Tokyo", month: "numeric", day: "numeric", weekday: "short" });
const time = new Intl.DateTimeFormat("ja-JP", { timeZone: "Asia/Tokyo", hour: "2-digit", minute: "2-digit", hour12: false });
const actionState = { not_open: "受付開始前", actionable: "対応できます", overdue: "対応が必要です" } as const;
const recruitmentState: Record<RecruitmentShift["state"], string> = { available: "募集中", available_with_warning: "要確認", not_eligible: "応募不可", applied: "応募済み", accepted_waiting_assignment: "採用済み", rejected: "見送り", withdrawn: "取下げ済み", capacity_full: "定員到達", deadline_passed: "募集終了" };

type Props = { displayName: string; assignments: WorkerAssignment[] | null; recruitment: RecruitmentShift[] | null };

export function WorkerHome({ displayName, assignments, recruitment }: Props) {
  const actionAssignment = assignments ? selectWorkerHomeNextAction(assignments) : null;
  const nextAction = actionAssignment?.timeline.nextAction ?? null;
  const endWorkAssignment = assignments && !nextAction ? selectWorkerHomeEndWork(assignments) : null;
  const nextShift = assignments ? selectWorkerHomeNextShift(assignments) : null;
  const recruitmentPreview = recruitment?.slice(0, 2) ?? [];
  return <main className="mx-auto w-full max-w-5xl px-5 py-7 sm:px-8 sm:py-10">
    <header className="px-1"><h1 className="text-[25px] font-semibold tracking-tight text-foreground md:sr-only">ホーム</h1><p className="mt-2 text-xs text-foreground-secondary md:mt-0">こんにちは、{displayName || "Worker"}さん</p></header>
    <div className="mt-2 grid gap-4 lg:grid-cols-[minmax(0,1.25fr)_minmax(280px,0.75fr)] lg:gap-6">
      <div className="min-w-0 space-y-4">
        <section className="rounded-card border border-border bg-surface p-4" aria-labelledby="worker-next-action"><p id="worker-next-action" className="text-xs text-foreground-secondary">今日やること</p>
          {assignments === null ? <HomeError message="勤務情報を取得できませんでした。" /> : nextAction && actionAssignment ? <><h2 className="mt-2 text-[15px] font-semibold text-foreground">{nextAction.label}</h2><p className="mt-2 text-sm text-foreground-secondary">{day.format(new Date(actionAssignment.startsAt))} {actionAssignment.projectName} / {actionAssignment.jobName}</p><p className={`mt-2 text-xs font-semibold ${nextAction.state === "overdue" ? "text-amber-700" : "text-link"}`}>{actionState[nextAction.state]}{nextAction.dueAt ? ` ・ ${time.format(new Date(nextAction.dueAt))}目安` : ""}</p><Link href={nextAction.href} className="mt-4 inline-flex min-h-11 w-full items-center justify-center rounded-control bg-link px-6 text-sm font-semibold text-white hover:bg-blue-800 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus-ring">{nextAction.label}</Link></> : endWorkAssignment ? <><h2 className="mt-2 text-[15px] font-semibold text-foreground">退勤を報告する</h2><p className="mt-2 text-sm text-foreground-secondary">{day.format(new Date(endWorkAssignment.startsAt))} {endWorkAssignment.projectName} / {endWorkAssignment.jobName}</p><p className="mt-2 text-xs font-semibold text-link">勤務中</p><Link href={`/worker/assignments/${endWorkAssignment.id}#attendance`} className="mt-4 inline-flex min-h-11 w-full items-center justify-center rounded-control bg-link px-6 text-sm font-semibold text-white hover:bg-blue-800 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus-ring">退勤報告へ</Link></> : <div className="py-3"><h2 className="text-[15px] font-semibold text-foreground">現在、対応が必要なActionはありません</h2><p className="mt-2 text-sm text-foreground-secondary">次の勤務予定は下で確認できます。</p></div>}
        </section>
        <section className="rounded-card border border-border bg-surface p-4" aria-labelledby="worker-next-shift"><p id="worker-next-shift" className="text-xs text-foreground-secondary">次の勤務</p>
          {assignments === null ? <HomeError message="勤務情報を取得できませんでした。" /> : nextShift ? <><div className="mt-2 flex flex-wrap items-start justify-between gap-2"><div className="min-w-0"><h2 className="text-[15px] font-semibold text-foreground">{day.format(new Date(nextShift.startsAt))} {nextShift.projectName}</h2><p className="mt-2 text-sm text-foreground-secondary">{time.format(new Date(nextShift.startsAt))}–{time.format(new Date(nextShift.endsAt))} ・ {nextShift.workplaceName}</p></div><PreShiftStatusBadge state={nextShift.confirmationState} /></div>{(nextShift.meetingAt || nextShift.meetingNote) && <p className="mt-4 font-semibold text-foreground">集合 {nextShift.meetingAt ? time.format(new Date(nextShift.meetingAt)) : "時刻未設定"}{nextShift.meetingNote ? ` ・ ${nextShift.meetingNote}` : ""}</p>}<Link href={`/worker/assignments/${nextShift.id}`} className="mt-4 inline-flex min-h-11 items-center text-sm font-semibold text-link underline-offset-4 hover:underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus-ring">勤務詳細を見る <span aria-hidden>›</span></Link></> : <div className="py-3"><h2 className="text-[15px] font-semibold text-foreground">勤務予定はありません</h2><p className="mt-2 text-sm text-foreground-secondary">募集中の勤務から新しい仕事を探せます。</p><div className="mt-4 flex flex-wrap gap-3"><Link href="/worker/recruitment" className="inline-flex min-h-11 items-center rounded-control bg-link px-5 text-sm font-semibold text-white">勤務を探す</Link><Link href="/worker/shifts" className="inline-flex min-h-11 items-center rounded-control border border-border-strong px-5 text-sm font-semibold">勤務一覧を見る</Link></div></div>}
        </section>
      </div>
      <section className="min-w-0" aria-labelledby="worker-recruitment-preview"><div className="flex items-center justify-between gap-4 px-1"><h2 id="worker-recruitment-preview" className="text-xl font-semibold text-foreground">募集中の仕事</h2><Link href="/worker/recruitment" className="inline-flex min-h-11 items-center text-sm font-semibold text-link">すべて見る <span aria-hidden>›</span></Link></div>
        {recruitment === null ? <div className="mt-2 rounded-card border border-border bg-surface p-4"><HomeError message="募集情報を取得できませんでした。" /></div> : recruitmentPreview.length ? <ul className="mt-2 divide-y divide-border overflow-hidden rounded-card border border-border bg-surface">{recruitmentPreview.map((item) => <li key={item.shiftId}><Link href={`/worker/recruitment/${item.shiftId}`} className="block min-h-24 p-4 hover:bg-surface-hover focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-focus-ring"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs text-foreground-secondary">{day.format(new Date(item.startsAt))}</p><h3 className="mt-1 truncate font-semibold text-foreground">{item.projectName} / {item.jobName}</h3><p className="mt-1 truncate text-sm text-foreground-secondary">{time.format(new Date(item.startsAt))}–{time.format(new Date(item.endsAt))} ・ {item.workplaceName}</p></div><span className="shrink-0 text-xs font-semibold text-emerald-700">{recruitmentState[item.state]}</span></div></Link></li>)}</ul> : <div className="mt-2 rounded-card border border-border bg-surface p-5"><p className="font-semibold text-foreground">現在募集中の勤務はありません</p><p className="mt-2 text-sm text-foreground-secondary">新しい募集が公開されると、ここに表示されます。</p></div>}
      </section>
    </div>
  </main>;
}

function HomeError({ message }: { message: string }) { return <div role="alert" className="py-3"><p className="font-semibold text-foreground">{message}</p><p className="mt-1 text-sm text-foreground-secondary">時間をおいて再度お試しください。</p></div>; }
