import type { SupabaseClient } from "@supabase/supabase-js";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
// @ts-expect-error Node native TypeScript requires suffix.
import { createActorClients, prepareAuthFixtures, readLocalConfig } from "./auth-fixtures.ts";
// @ts-expect-error Node native TypeScript requires suffix.
import { IDS } from "./test-data.ts";
// @ts-expect-error Node native TypeScript requires suffix.
import { tokyoLocalToIso } from "../../lib/admin/attendance/attendance-confirmation-schema.ts";

const config = readLocalConfig(); const results: boolean[] = []; const uid = () => crypto.randomUUID();
const record = (n: string, pass: boolean, actual: string) => { results.push(pass); console.log(`ATTENDANCE-CONFIRM-${n} ${pass ? "PASS" : "FAIL"}: ${actual}`); };
function sql(value: string) { return execFileSync("docker", ["exec", "-i", "supabase_db_dispatch-os", "psql", "-U", "postgres", "-d", "postgres", "-At", "-v", "ON_ERROR_STOP=1"], { input: value, encoding: "utf8" }).trim(); }
function fixture(options: { job?: string; worker?: string; status?: string; start?: string; end?: string; breakMinutes?: number } = {}) { const shiftId = uid(); const assignmentId = uid(); const start = options.start ?? "2026-08-22T00:00:00Z"; const end = options.end ?? "2026-08-22T09:00:00Z"; sql(`insert into public.shift_slots(id,job_id,starts_at,ends_at,required_workers,break_minutes,status) values('${shiftId}','${options.job ?? IDS.jobs.n1}','${start}','${end}',1,${options.breakMinutes ?? 60},'recruiting'); insert into public.assignments(id,shift_slot_id,worker_id,source,status,assigned_by) values('${assignmentId}','${shiftId}','${options.worker ?? IDS.workers.workerA}','manager','${options.status ?? "assigned"}','${IDS.users.managerA}');`); return { shiftId, assignmentId, start, end }; }
function events(id: string, start?: string, end?: string) { if (start) sql(`insert into public.attendance_events(assignment_id,event_type,server_received_at,source) values('${id}','start_work','${start}','worker');`); if (end) sql(`insert into public.attendance_events(assignment_id,event_type,server_received_at,source) values('${id}','end_work','${end}','worker');`); }
const confirm = (client: SupabaseClient, id: string, start: string, end: string, breaks = 60, reason: string | null = null) => client.rpc("confirm_attendance_record", { p_assignment_id: id, p_actual_start_at: start, p_actual_end_at: end, p_break_minutes: breaks, p_adjustment_reason: reason });
const absent = (client: SupabaseClient, shift: string, id: string) => client.rpc("mark_assignment_absent", { p_shift_id: shift, p_assignment_id: id });
const noShow = (client: SupabaseClient, shift: string, id: string) => client.rpc("mark_assignment_no_show", { p_shift_id: shift, p_assignment_id: id });
const count = (table: string, id: string) => Number(sql(`select count(*) from public.${table} where assignment_id='${id}';`)); const status = (id: string) => sql(`select status from public.assignments where id='${id}';`);
await prepareAuthFixtures(config); const clients = await createActorClients(config);
async function basic(n: string, client: SupabaseClient, options: Parameters<typeof fixture>[0] = {}, success = true) { const f = fixture(options); const r = await confirm(client, f.assignmentId, f.start, f.end, options.breakMinutes ?? 60, "管理者入力"); record(n, success ? !r.error : Boolean(r.error), r.error?.message ?? "confirmed"); return f; }
await basic("001", clients.managerA); await basic("002", clients.systemAdmin, { job: IDS.jobs.t1, worker: IDS.workers.workerC }); await basic("003", clients.workerA, {}, false); await basic("004", clients.anon, {}, false); await basic("005", clients.managerA, { job: IDS.jobs.t1, worker: IDS.workers.workerC }, false);
{ const f=fixture(); events(f.assignmentId,f.start,f.end); const r=await confirm(clients.managerA,f.assignmentId,f.start,f.end,60); record("006",!r.error,r.error?.message??"start/end"); }
{ const f=fixture(); events(f.assignmentId,f.start); const r=await confirm(clients.managerA,f.assignmentId,f.start,f.end,60,"退勤補正"); record("007",!r.error,r.error?.message??"start only"); }
await basic("008",clients.managerA); { const f=fixture(); events(f.assignmentId,undefined,f.end); const r=await confirm(clients.managerA,f.assignmentId,f.start,f.end,60,"補正"); record("009",Boolean(r.error),r.error?.message??"unexpected"); }
for (const [n,s,e] of [["010","2026-08-22T00:00:00Z","2026-08-22T00:00:00Z"],["011","2026-08-22T01:00:00Z","2026-08-22T00:00:00Z"]] as const) { const f=fixture(); const r=await confirm(clients.managerA,f.assignmentId,s,e,0,"補正"); record(n,Boolean(r.error),r.error?.message??"unexpected"); }
await basic("012",clients.managerA,{start:"2026-08-22T13:00:00Z",end:"2026-08-22T21:00:00Z"}); await basic("013",clients.managerA,{breakMinutes:0});
for (const [n,b] of [["014",-1],["015",541]] as const) { const f=fixture(); const r=await confirm(clients.managerA,f.assignmentId,f.start,f.end,b,"補正"); record(n,Boolean(r.error),r.error?.message??"unexpected"); }
{ const f=fixture(); events(f.assignmentId,f.start,f.end); const r=await confirm(clients.managerA,f.assignmentId,f.start,f.end,60); record("016",!r.error,r.error?.message??"unchanged"); }
for (const [n,kind,reason,ok] of [["017","start",null,false],["018","start","開始補正",true],["019","end",null,false],["020","end","終了補正",true],["021","break",null,false],["022","break","休憩補正",true]] as const) { const f=fixture(); events(f.assignmentId,f.start,f.end); const s=kind==="start"?"2026-08-22T00:01:00Z":f.start; const e=kind==="end"?"2026-08-22T08:59:00Z":f.end; const b=kind==="break"?30:60; const r=await confirm(clients.managerA,f.assignmentId,s,e,b,reason); record(n,ok?!r.error:Boolean(r.error),r.error?.message??"result"); }
{ const f=fixture(); const r=await confirm(clients.managerA,f.assignmentId,f.start,f.end,60); record("023",Boolean(r.error),r.error?.message??"unexpected"); }
const side=fixture({status:"confirmed"}); const app=uid(); sql(`insert into public.shift_applications(id,shift_slot_id,worker_id,status) values('${app}','${side.shiftId}','${IDS.workers.workerA}','accepted');`); const eventBefore=sql(`select count(*)||'|'||coalesce(string_agg(event_type||server_received_at||source,',' order by server_received_at),'') from public.attendance_events where assignment_id='${side.assignmentId}';`); const shiftBefore=sql(`select status||'|'||required_workers||'|'||starts_at||'|'||ends_at from public.shift_slots where id='${side.shiftId}';`); await confirm(clients.managerA,side.assignmentId,side.start,side.end,60,"管理者入力");
record("024",count("attendance_records",side.assignmentId)===1,"records=1"); const twice=await confirm(clients.managerA,side.assignmentId,side.start,side.end,60,"again"); record("025",Boolean(twice.error)&&count("attendance_records",side.assignmentId)===1,twice.error?.message??"unexpected"); record("026",status(side.assignmentId)==="completed",status(side.assignmentId)); record("027",status(side.assignmentId)==="completed","confirmed -> completed"); record("028",sql(`select count(*)||'|'||coalesce(string_agg(event_type||server_received_at||source,',' order by server_received_at),'') from public.attendance_events where assignment_id='${side.assignmentId}';`)===eventBefore,eventBefore); record("029",sql(`select status from public.shift_applications where id='${app}';`)==="accepted","accepted"); record("030",sql(`select status||'|'||required_workers||'|'||starts_at||'|'||ends_at from public.shift_slots where id='${side.shiftId}';`)===shiftBefore,"unchanged");
for (const [n,st] of [["031","absent"],["032","no_show"],["033","cancelled_by_worker"],["034","cancelled_by_company"],["035","completed"]] as const) await basic(n,clients.managerA,{status:st},false);
{ const f=fixture(); const race=await Promise.all([confirm(clients.managerA,f.assignmentId,f.start,f.end,60,"入力"),confirm(clients.managerA,f.assignmentId,f.start,f.end,60,"入力")]); record("036",race.filter(r=>!r.error).length===1&&count("attendance_records",f.assignmentId)===1,`success=${race.filter(r=>!r.error).length}`); }
let endRace=""; { const now=new Date(); const s=new Date(now.getTime()-300000).toISOString(); const e=new Date(now.getTime()+3600000).toISOString(); const f=fixture({start:s,end:e}); events(f.assignmentId,s); const race=await Promise.all([clients.workerA.rpc("record_worker_end_work",{p_assignment_id:f.assignmentId}),confirm(clients.managerA,f.assignmentId,s,e,0,"管理者確定")]); endRace=`success=${race.filter(r=>!r.error).length},records=${count("attendance_records",f.assignmentId)},end=${Number(sql(`select count(*) from public.attendance_events where assignment_id='${f.assignmentId}' and event_type='end_work';`))}`; record("037",count("attendance_records",f.assignmentId)===1&&status(f.assignmentId)==="completed",endRace); }
let absentRace=""; { const f=fixture(); const race=await Promise.all([absent(clients.managerA,f.shiftId,f.assignmentId),confirm(clients.managerA,f.assignmentId,f.start,f.end,60,"入力")]); absentRace=`success=${race.filter(r=>!r.error).length},status=${status(f.assignmentId)}`; record("038",race.filter(r=>!r.error).length===1,absentRace); }
let noShowRace=""; { const now=new Date(); const f=fixture({start:new Date(now.getTime()-60000).toISOString(),end:new Date(now.getTime()+3600000).toISOString()}); const race=await Promise.all([noShow(clients.managerA,f.shiftId,f.assignmentId),confirm(clients.managerA,f.assignmentId,f.start,f.end,0,"入力")]); noShowRace=`success=${race.filter(r=>!r.error).length},status=${status(f.assignmentId)}`; record("039",race.filter(r=>!r.error).length===1,noShowRace); }
const audit=sql(`select approved_by||'|'||(approved_at between created_at-interval '1 second' and clock_timestamp()+interval '1 second') from public.attendance_records where assignment_id='${side.assignmentId}';`); record("040",audit.startsWith(IDS.users.managerA),audit); record("041",audit.endsWith("|true"),audit);
record("042",tokyoLocalToIso("2026-08-22","09:00")==="2026-08-22T00:00:00.000Z","JST->UTC"); record("043",tokyoLocalToIso("2026-08-31","22:00")==="2026-08-31T13:00:00.000Z"&&tokyoLocalToIso("2026-09-01","06:00")==="2026-08-31T21:00:00.000Z","month crossing"); record("044",(Date.parse(side.end)-Date.parse(side.start))/60000-60===480,"8h00m");
const page=readFileSync("components/admin/attendance/attendance-detail-view.tsx","utf8"), form=readFileSync("components/admin/attendance/attendance-confirmation-form.tsx","utf8"), list=readFileSync("components/admin/attendance/attendance-list.tsx","utf8"), action=readFileSync("app/actions/attendance.ts","utf8"), dal=readFileSync("lib/admin/attendance/get-attendance-detail.ts","utf8"); record("045",page.includes("Worker打刻")&&form.includes("確定勤務実績"),"detail sections"); record("046",list.includes("勤怠詳細"),"detail link"); record("047",page.includes("勤怠確定済み")&&page.includes("detail.record ?"),"read only"); record("048",action.includes("最新の勤務状況を確認して")&&!action.includes("return { ok: false, message: error"),"general error"); record("049",(dal.match(/\.from\(/g)?.length??0)===3,"3 batched queries"); record("050",config.url.startsWith("http://127.0.0.1")||config.url.startsWith("http://localhost"),config.url);
console.log(`END-RACE=${endRace}\nABSENT-RACE=${absentRace}\nNO-SHOW-RACE=${noShowRace}`); const passed=results.filter(Boolean).length; console.log(`TOTAL=${results.length} PASSED=${passed} FAILED=${results.length-passed}`); if(passed!==results.length)process.exitCode=1;
