import type { SupabaseClient } from "@supabase/supabase-js";
import { execFileSync } from "node:child_process";
// @ts-expect-error Node native TypeScript requires suffix.
import { createActorClients, prepareAuthFixtures, readLocalConfig } from "./auth-fixtures.ts";
// @ts-expect-error Node native TypeScript requires suffix.
import { IDS } from "./test-data.ts";

const config = readLocalConfig(); const results: boolean[] = []; const uid = () => crypto.randomUUID();
const record = (id: string, pass: boolean, actual: string) => { results.push(pass); console.log(`ATTENDANCE-REVISION-${id} ${pass ? "PASS" : "FAIL"}: ${actual}`); };
function sql(value: string) { return execFileSync("docker", ["exec", "-i", "supabase_db_dispatch-os", "psql", "-U", "postgres", "-d", "postgres", "-At", "-v", "ON_ERROR_STOP=1"], { input: value, encoding: "utf8" }).trim(); }
function fixture(options: { job?: string; worker?: string; status?: string; record?: boolean } = {}) { const shiftId=uid(), assignmentId=uid(), recordId=uid(); const start="2026-08-22T00:00:00Z", end="2026-08-22T09:00:00Z"; sql(`insert into public.shift_slots(id,job_id,starts_at,ends_at,required_workers,break_minutes,status) values('${shiftId}','${options.job??IDS.jobs.n1}','${start}','${end}',1,60,'recruiting'); insert into public.assignments(id,shift_slot_id,worker_id,source,status,assigned_by) values('${assignmentId}','${shiftId}','${options.worker??IDS.workers.workerA}','manager','${options.status??"completed"}','${IDS.users.managerA}'); ${options.record===false?"":`insert into public.attendance_records(id,assignment_id,planned_start_at,planned_end_at,actual_start_at,actual_end_at,total_break_minutes,status,approved_at,approved_by,adjustment_reason) values('${recordId}','${assignmentId}','${start}','${end}','${start}','${end}',60,'approved',now(),'${IDS.users.managerA}','initial');`}`); return {shiftId,assignmentId,recordId,start,end}; }
const revise=(client:SupabaseClient,id:string,start:string,end:string,breaks=30,reason="訂正")=>client.rpc("revise_attendance_record",{p_assignment_id:id,p_actual_start_at:start,p_actual_end_at:end,p_break_minutes:breaks,p_reason:reason});
await prepareAuthFixtures(config); const clients=await createActorClients(config);
async function basic(n:string,client:SupabaseClient,options:Parameters<typeof fixture>[0]={},success=true){const f=fixture(options);const r=await revise(client,f.assignmentId,"2026-08-22T00:10:00Z",f.end);record(n,success?!r.error:Boolean(r.error),r.error?.message??"revised");return f;}
await basic("001",clients.managerA); await basic("002",clients.systemAdmin,{job:IDS.jobs.t1,worker:IDS.workers.workerC}); await basic("003",clients.workerA,{},false); await basic("004",clients.anon,{},false);
sql(`update public.profiles set is_active=false where id='${IDS.users.managerA}';`); await basic("005",clients.managerA,{},false); sql(`update public.profiles set is_active=true where id='${IDS.users.managerA}';`); await basic("006",clients.managerA,{job:IDS.jobs.t1,worker:IDS.workers.workerC},false);
await basic("007",clients.managerA); for(const [n,status] of [["008","assigned"],["009","confirmed"],["010","absent"],["011","no_show"],["012","cancelled_by_worker"],["013","cancelled_by_company"]] as const) await basic(n,clients.managerA,{status},false); await basic("014",clients.managerA,{record:false},false);
for(const [n,s,e,b] of [["015","2026-08-22T00:10:00Z","2026-08-22T09:00:00Z",60],["016","2026-08-22T00:00:00Z","2026-08-22T09:10:00Z",60],["017","2026-08-22T00:00:00Z","2026-08-22T09:00:00Z",30],["018","2026-08-22T00:10:00Z","2026-08-22T09:10:00Z",30]] as const){const f=fixture();const r=await revise(clients.managerA,f.assignmentId,s,e,b);record(n,!r.error,r.error?.message??"revised");}
{const f=fixture();const r=await revise(clients.managerA,f.assignmentId,f.start,f.end,60);record("019",Boolean(r.error),r.error?.message??"unexpected");}
for(const [n,reason,ok] of [["020","",false],["021","   ",false],["022","通常理由",true],["023","a".repeat(500),true],["024","a".repeat(501),false]] as const){const f=fixture();const r=await revise(clients.managerA,f.assignmentId,"2026-08-22T00:01:00Z",f.end,60,reason);record(n,ok?!r.error:Boolean(r.error),r.error?.message??"result");}
for(const [n,s,e,b,ok] of [["025","2026-08-22T09:00:00Z","2026-08-22T09:00:00Z",0,false],["026","2026-08-22T10:00:00Z","2026-08-22T09:00:00Z",0,false],["027","2026-08-22T13:00:00Z","2026-08-22T21:00:00Z",0,true],["028","2026-08-31T13:00:00Z","2026-08-31T21:00:00Z",0,true],["029","2026-08-22T00:00:00Z","2026-08-22T09:01:00Z",0,true],["030","2026-08-22T00:00:00Z","2026-08-22T09:01:00Z",-1,false],["031","2026-08-22T00:00:00Z","2026-08-22T09:01:00Z",542,false]] as const){const f=fixture();const r=await revise(clients.managerA,f.assignmentId,s,e,b);record(n,ok?!r.error:Boolean(r.error),r.error?.message??"result");}
const audit=fixture(); const before=sql(`select approved_by||'|'||approved_at||'|'||adjustment_reason from public.attendance_records where id='${audit.recordId}'`); const eventsBefore=sql(`select count(*) from public.attendance_events where assignment_id='${audit.assignmentId}'`); const shiftBefore=sql(`select status||'|'||required_workers from public.shift_slots where id='${audit.shiftId}'`); await revise(clients.managerA,audit.assignmentId,"2026-08-22T00:15:00Z",audit.end,45,"監査訂正"); const row=sql(`select count(*) over()||'|'||before_actual_start_at||'|'||after_actual_start_at||'|'||changed_by||'|'||(changed_at<=clock_timestamp()) from public.attendance_record_revisions where assignment_id='${audit.assignmentId}'`);
record("032",row.startsWith("1|"),row); record("033",row.includes("|2026-08-22 00:00:00+00|"),row); record("034",row.includes("|2026-08-22 00:15:00+00|"),row); record("035",row.includes(IDS.users.managerA),row); record("036",row.endsWith("|true"),row); record("037",sql(`select actual_start_at||'|'||total_break_minutes from public.attendance_records where id='${audit.recordId}'`).includes("00:15:00+00|45"),"after stored"); const after=sql(`select approved_by||'|'||approved_at||'|'||adjustment_reason from public.attendance_records where id='${audit.recordId}'`); record("038",after.split("|")[0]===before.split("|")[0],after); record("039",after.split("|")[1]===before.split("|")[1],after); record("040",after.split("|")[2]===before.split("|")[2],after); record("041",sql(`select status from public.assignments where id='${audit.assignmentId}'`)==="completed","completed"); record("042",sql(`select count(*) from public.attendance_events where assignment_id='${audit.assignmentId}'`)===eventsBefore,"unchanged"); record("043",sql(`select status||'|'||required_workers from public.shift_slots where id='${audit.shiftId}'`)===shiftBefore,"unchanged");
const direct=await clients.managerA.from("attendance_record_revisions").insert({}); record("044",Boolean(direct.error),direct.error?.message??"unexpected"); const up=await clients.managerA.from("attendance_record_revisions").update({reason:"x"}).eq("id",uid()); record("045",Boolean(up.error),up.error?.message??"unexpected"); const del=await clients.managerA.from("attendance_record_revisions").delete().eq("id",uid()); record("046",Boolean(del.error),del.error?.message??"unexpected"); const own=await clients.managerA.from("attendance_record_revisions").select("id").eq("assignment_id",audit.assignmentId); record("047",!own.error&&own.data.length===1,`rows=${own.data?.length}`); const tokyo=fixture({job:IDS.jobs.t1,worker:IDS.workers.workerC}); await revise(clients.systemAdmin,tokyo.assignmentId,"2026-08-22T00:10:00Z",tokyo.end); const other=await clients.managerA.from("attendance_record_revisions").select("id").eq("assignment_id",tokyo.assignmentId); record("048",!other.error&&other.data.length===0,`rows=${other.data?.length}`); const admin=await clients.systemAdmin.from("attendance_record_revisions").select("id").eq("assignment_id",audit.assignmentId); record("049",!admin.error&&admin.data.length===1,`rows=${admin.data?.length}`); const worker=await clients.workerA.from("attendance_record_revisions").select("id").eq("assignment_id",audit.assignmentId); record("050",!worker.error&&worker.data.length===0,`rows=${worker.data?.length}`);
{const f=fixture();const race=await Promise.all([revise(clients.managerA,f.assignmentId,"2026-08-22T00:10:00Z",f.end,60,"A"),revise(clients.managerA,f.assignmentId,"2026-08-22T00:20:00Z",f.end,60,"B")]);const chain=sql(`select bool_and(lag_after is null or before_actual_start_at=lag_after) from (select before_actual_start_at,lag(after_actual_start_at) over(order by changed_at,id) lag_after from public.attendance_record_revisions where assignment_id='${f.assignmentId}') s`);record("CONCURRENCY-001",race.every(r=>!r.error)&&chain==="t",`success=${race.filter(r=>!r.error).length},chain=${chain}`);}
{const f=fixture();const race=await Promise.all([revise(clients.managerA,f.assignmentId,"2026-08-22T00:10:00Z",f.end,60,"same"),revise(clients.managerA,f.assignmentId,"2026-08-22T00:10:00Z",f.end,60,"same")]);record("CONCURRENCY-002",race.filter(r=>!r.error).length===1,`success=${race.filter(r=>!r.error).length}`);}
const passed=results.filter(Boolean).length; console.log(`TOTAL=${results.length} PASSED=${passed} FAILED=${results.length-passed}`); if(passed!==results.length) process.exitCode=1;
